### ISSUE TITLE
Add visualization to MeasureObjectRadialDistribution

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1255]
[This Forum user](http://www.cellprofiler.org/forum/viewtopic.php?f=14&t=4025&p=12104&sid=91449aa43e7683d8562a36d329335819#p12104) asked about visualizing the output of MeasureObjectRadialDistribution.  I would like to see one as well.  We used to have a distance transform figure, which wasn't that informative really, but a more veridical representation would be useful.

It would be useful to see both:
(1) The widths of each annulus, whether scaled or not, displayed on each object
(2) The value of either (or better, both!) FracAtD or MeanFrac as an intensity on each annulus

**Comment by 0James** [comment]
I am an avid CellProfiler user and really rather desperate to be able to visualise at least bin outline and ideally a heat-map. Somebody said this may not be useful because of the number of objects, however I am 'tricking' CellProfiler into thinking that an entire organ is one cell so that I can measure changing intensity of a marker throughout the organ under different circumstances - but I really really need the features LeeKamentsky has been playing with above. Publishing my results would be extremely difficult without these features.

I gather they are not in the current build (rev 6c2d896) - are they in a branch somewhere on here, I looked around but couldn't see anything? Lee, if you see this, do you have a compiled version that allows these heat-maps and bin visualisation? Or at least the source? I do not speak Python so really cannot do this myself.

I would be extremely grateful if anybody could help me.

**Comment by dlogan** [comment]
@0James : You should be able to download a trunk build here (http://www.cellprofiler.org/cgi-bin/trunk_build.cgi) and get this functionality.  Follow Lee's directions above in the Github issue.  

Side-note: We prefer that queries like these go to our CellProfiler Forum (http://cellprofiler.org/forum) so other non-power users might benefit, too.  Thanks!

**Comment by 0James** [comment]
@dlogan Thanks for your reply. I just installed the trunk build (2.1.2 rev 61075a2) and it does not have any of this functionality at all (outlines, heatmaps, etc), the module appears identical to the stable build.

I did try to build the developer's version myself so I could at least try and implement/tweak the functionality I need but it seems brew won't work on OS X 10.10 due to a lack of Ruby 1.8 framework apparently and I can't find a fix.

And sorry, I will use the forum in future, although [this](http://www.cellprofiler.org/forum/viewtopic.php?f=14&t=4025&p=12104&sid=91449aa43e7683d8562a36d329335819#p12104) thread already covered it, so I'd be repeating what was already said, so I just needed to find a build containing the functionality. I will happily reply to that thread with details on accessing this feature for non-power users that may need it if I am able to figure that out for myself.

**Comment by braymp** [comment]
I'm guessing that the infrastructure to support the lines/heatmap was added (right-click on the bottom-left panel in the IdentifyPrimary display window to see it in action), but incorporating it into MeasureRadialDistribution has yet to be done.

**Comment by 0James** [comment]
@braymp It appears so - but the code exists as evidenced by the very nice heat-maps above, unfortunately without being able to install the developer's edition I don't see how I can implement it. It seems scientifically untenable to present data measuring radial distribution if you can't determine where the bins have been drawn, even if I leave aside the notion of visualising the data...

**Comment by LeeKamentsky** [comment]
There's FracAtD, MeanFrac and RadialCV measurements and you can choose multiple objects, images and bins, so there are quite a lot of things that might be displayed. I'd vote for adding a section which would let you pick one object category, one image and one binning and have that displayed as a heatmap with buttons to add and remove the displays (with the default being don't display any). I can probably implement this sometime in the next week.

**Comment by 0James** [comment]
@LeeKamentsky That makes sense, and would be very valuable. At a minimum, outlines of any given single set of bins should be available for display - in many applications that come to mind, no awareness of bin/annulus location would cause problems demonstrating that the analysis is valid (or rather, that the conclusions drawn therefrom are valid).

Sincere thanks for making this more of a priority.

**Comment by LeeKamentsky** [comment]
@0James - it's being built now. There is an "add heatmap" button that lets you pick a combination of image / objects / measurement to display. The display is shown when you run in test mode and you can have the module output the heatmap as an image and save it via SaveImages.

**Comment by braymp** [comment]
Just go an error using the new display. To replicate:
* Load welcome screen pipeline, and insert MeasureRadialDistribution
* Set image to CropBlue and objects to Nuclei. Leave other settings at defaults.
* Press "Add another heatmap" button. Leave settings at defaults.
```
Traceback (most recent call last):
  File "C:\Trunk\CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2812, in do_step
    module.display(workspace, fig)
  File "C:\Trunk\CellProfiler\cellprofiler\modules\measureobjectradialdistribution.py", line 475, in display
    colorbar = True)
  File "C:\Trunk\CellProfiler\cellprofiler\gui\cpfigure.py", line 221, in wrapper
    return fn(*args, **kwargs)
  File "C:\Trunk\CellProfiler\cellprofiler\gui\cpfigure.py", line 1184, in subplot_imshow
    self.clear_subplot(x, y)
  File "C:\Trunk\CellProfiler\cellprofiler\gui\cpfigure.py", line 792, in clear_subplot
    if not self.subplots[x,y]:
IndexError: index 1 is out of bounds for axis 1 with size 1
```
