### ISSUE TITLE
CP fails to open on Mac OSX 10.10.1 (Yosemite)

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1297]
A couple of forum users have reported being unable to run CP on Yosemite, both the 2.1.1 release and from source. Failure seems to occur for different reasons, though: 
http://cellprofiler.org/forum/viewtopic.php?f=16&t=4012&p=12449#p12429
http://cellprofiler.org/forum/viewtopic.php?f=16&t=4144

However, at least one user has been successful: http://cellprofiler.org/forum/viewtopic.php?f=16&t=4100&p=12302#p12302

**Comment by LeeKamentsky** [comment]
I was able to run CellProfiler 2.1.1 on a Yosemite machine after installing the legacy Java 6 SE ( see issue #1312). It appears to work normally (89 of 96 SBS image sets processed in 9 minutes, no GUI problems). Szymon's problem is something that needs to be addressed by the setup script and is probably not a Yosemite problem.

**Comment by LeeKamentsky** [comment]
I'm going to close this and keep issue #1299 open. I think both forum users' issues have been addressed.

**Comment by AnneCarpenter** [comment]
When I load the project, remove the listed files, and add this image to the file list, then Analyze Images, I get a CP error (with choices: open console or terminate).  (sent image and project file to Lee directly)

I'm using v 2.1.2 (00a8678, Aug 2015) so not sure if it's a pipeline being newer than my version of CP perhaps or a bug that has subsequently been fixed.

Here is what console says - see appendix (a).  But at another point I got a few other errors about version number - see (b) - that seems to be an error upon startup that doesn't cause any noticeable problem in the UI.

I then grabbed the trunk build from Sept 8, as it's the latest I have access to. I got the same errors.

(a)
11/5/15 9:07:10.681 PM CellProfiler[10919]: GetDYLDEntryPointWithImage(/System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete,CacheDeleteCopyPurgeableSpaceWithInfo) failed.
11/5/15 9:07:58.217 PM CellProfiler[10935]: CellProfiler Error

(b)
11/5/15 9:01:46.145 PM CellProfiler[10785]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.10.5. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
11/5/15 9:01:46.146 PM CellProfiler[10785]: 0   CarbonCore                          0x92d46291 ___Gestalt_SystemVersion_block_invoke + 135
11/5/15 9:01:46.146 PM CellProfiler[10785]: 1   libdispatch.dylib                   0x92bf93b7 dispatch_once_f + 251
11/5/15 9:01:46.146 PM CellProfiler[10785]: 2   libdispatch.dylib                   0x92bf9477 dispatch_once + 31
11/5/15 9:01:46.146 PM CellProfiler[10785]: 3   CarbonCore                          0x92cbf69d _Gestalt_SystemVersion + 1050
11/5/15 9:01:46.146 PM CellProfiler[10785]: 4   CarbonCore                          0x92cbe7c0 Gestalt + 150
11/5/15 9:01:46.146 PM CellProfiler[10785]: 5   libwx_macud-2.8.0.8.0.dylib         0x0782e14b _Z14UMAInitToolboxtb + 43
11/5/15 9:01:46.146 PM CellProfiler[10785]: 6   libwx_macud-2.8.0.8.0.dylib         0x07845123 _ZN5wxApp10InitializeERiPPw + 65

**Comment by AnneCarpenter** [comment]
A search for GetDYLDEntryPointWithImage and Gestalt in our repository did not yield any issues.

**Comment by AnneCarpenter** [comment]
p.s. I'm running 10.10.5 (14F1021)

**Comment by LeeKamentsky** [comment]
See http://159.203.141.247/t/cp-not-able-to-start/2463/3

https://discussions.apple.com/thread/6656667?start=0&tstart=0

From what I can gather, the cellprofiler that we just built has gone incompatible on the operating system that Apple just released. I can run software from 1995 on my PC just fine though. The problem will probably go away when we move to 64 bits and then return again sometime in the near future unless you switch OS's.

**Comment by LeeKamentsky** [comment]
If CP has stopped working, I would try deleting your preferences. But the root of it is that you should try the new 64 bit version. I don't know if you have enough time to follow the developer recipe, but if you did, I think you would find that the problem doesn't happen.

**Comment by dlogan** [comment]
mv ~/Library/Preferences/CellProfilerLocal.cfg ~/CellProfilerLocal.cfg.BACKUP

then restart CP.

**Comment by AnneCarpenter** [comment]
I tried David's trick, restarted my laptop and CP but the problem remained
so indeed I will put it on my list to do the dev version (or wait til you
have a build of a newer version ready for me to test).

**Comment by dlogan** [comment]
Not sure if this helps or just confuses, but I just ran this pipeline ok on the release build, i.e. 2.1.1, on my Yosemite Mac.

**Comment by 0x00B1** [comment]
This has been resolved. If you disagree, please re-open.
