### ISSUE TITLE
Workspace viewer: Validation error when items go missing?

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1313]
I was inspecting an image in the viewer, and then changed the name of that image in the pipeline. The viewer didn't seem to notice; it still allowed to me to pick it/display it, though the new name was also listed in the drop-down. 

Perhaps a validation error for the drop-down (i.e, have it turn red) as in the main pipeline? Then again, if nothing breaks, it may not be a big deal...

**Comment by LeeKamentsky** [comment]
The workspace viewer looks at the workspace and if you change the image name while executing a cycle, the old image is still there in the workspace. If you hit "Next Image Set", you'll find that the old image name is missing from the menu. I think this is best because someone might inadvertently change the name and be annoyed that the associated image was jettisoned because of that.

**Comment by braymp** [comment]
Fair enough. Closing until someone other than me puts up a fuss :-)
