### ISSUE TITLE
Metadata: Unable to match csv

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1347]
From this forum post: http://cellprofiler.org/forum/viewtopic.php?f=16&t=4031

The attached pipeline uses file/folder metadata to match to the attached csv. Everything looks correct re: regexp and csv syntax, however, the Metadata module is not importing the data, i.e, the csv Condition col doesn't show up upon hitting the "Update" button in the module. 

For good measure, I re-created the forum user's pipeline from scratch, to make sure there's not a project caching issue as the culprit, but no luck.

Attachments:
http://cellprofiler.org/issues/uploaded/wHakeP/issue.cppipe
http://cellprofiler.org/issues/uploaded/zt62yS/testplatemap.csv

**Comment by LeeKamentsky** [comment]
The problem here is that the user is extracting the well row and the well column from the filename rather than the well. The metadata module runs its extractors in order and it runs the well row / well column -> well extractor last, so "well" is not available when the matching is done despite the fact that "Well" is in the list.

So the work-around is to have WellColumn and WellRow metadata columns in the CSV file if that would work.
