### ISSUE TITLE
Dateutil package on Linux not updating 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1359]
[This Forum user](http://www.cellprofiler.org/forum/viewtopic.php?f=14&t=4301#p13024) reports ```yum update``` fails to update cellprofiler-dateutil.  They can choose to not update this, but we should get this to work sometime.

Terminal output:
```
root@localhost]# yum update
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Update Process
Loading mirror speeds from cached hostfile
* base: mirror.sanctuaryhost.com
* epel: mirror.compevo.com
* extras: mirror.ubiquityservers.com
* updates: distro.ibiblio.org
Resolving Dependencies
--> Running transaction check
---> Package cellprofiler-dateutil.x86_64 0:2.2-1 will be updated
--> Processing Dependency: cellprofiler-dateutil = 2.2-1 for package: cellprofiler-2.1.1-2.x86_64
---> Package cellprofiler-dateutil.x86_64 0:2.2-2 will be an update
--> Finished Dependency Resolution
Error: Package: cellprofiler-2.1.1-2.x86_64 (@cellprofiler)
Requires: cellprofiler-dateutil = 2.2-1
Removing: cellprofiler-dateutil-2.2-1.x86_64 (@cellprofiler)
cellprofiler-dateutil = 2.2-1
Updated By: cellprofiler-dateutil-2.2-2.x86_64 (cellprofiler)
cellprofiler-dateutil = 2.2-2
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

[root@localhost]# rpm -qa cellprofiler
cellprofiler-2.1.1-2.x86_64

[root@localhost]# rpm -qa cellprofiler-dateutil
cellprofiler-dateutil-2.2-1.x86_64
```

**Comment by LeeKamentsky** [comment]
I replied to the user on the forum. I think I'd rather not fix this - the issue is that we use the repository for all versions of CellProfier and there are bound to be updates to dependencies that will cause this sort of problem. I like the idea of CellProfiler X.Y.Z having a fixed set of dependencies for reproducibility so that when someone says, "I'm using CellProfiler X.Y.Z on Centos", I know exactly which dependencies they have and can reproduce the problem.
To fix, we would have to re-release CellProfiler 2.1.1 or use separate repositories for each release.
