### ISSUE TITLE
For measurement modules that display a chart, make clear the fact that an aggregate is shown

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1373]
For the Nth time, someone misunderstood that the chart shown by a measurement module contains the aggregate values and thought it was the actual result (in this case, MeasureObjectIntensity _and_ CalculateMath). You'd think the the module name and the mean/median/std as headers would clear that up, but alas no...

Any suggestions as to how to make this absolutely clear? For example, could we put text above the chart saying "Values shown are per-image aggregates of the per-object values)"?

**Comment by LeeKamentsky** [comment]
I'd have a header that would appear to be useful, but would really be there to solve the issue, maybe "Aggregates for 215 cells" or "Aggregate measurements: 215 cells". That way, it avoids the obvious question of why say something obvious.

**Comment by braymp** [comment]
I like that, perhaps "Per-image aggregate measurements of N objects" to make it clear what level the aggregate is being done.

But since multiple objects can be used, strictly speaking, it'd have to be "...of N1 <object_name1>, N2 <object_name2>,...", which can get rather long.

**Comment by dlogan** [comment]
How about another solution altogether -- visualization.  Lose the text and use small boxplots instead.  Probably too much overhead in computation as well as screen real estate, but it would solve the issue at hand (I think) as well as provide a possibly more meaningful data display.

**Comment by AnneCarpenter** [comment]
If you show something nice like a boxplot, people will then rightly ask how
they can save the results of that visualization. I suspect it's best to
just leave it as text.


Anne E. Carpenter, Ph.D.
Director, Imaging Platform
Broad Institute of Harvard and MIT
415 Main Street,
Cambridge MA 02142

phone: (617) 714-7750
anne@broadinstitute.org
http://www.broadinstitute.org/~anne

**Comment by LeeKamentsky** [comment]
I guess this is what CPA or R is for... but we already have DisplayDensityPlot, DisplayHistogram and DisplayScatterPlot. It would not be much work to have a DisplayBoxPlot module as well and there is precedence for it. If people think it's a good idea, make a new issue.

**Comment by AnneCarpenter** [comment]
I think adding simple line of text above the chart suffices: "To view individual object measurements, use an Export module". 

Here are the modules which need this:
MeasureNeurons
MeasureObjectIntensity
MeasureObjectIntensityDistribution
MeasureObjectNeighbors
MeasureObjectSizeShape

Some modules need slightly different text because in any given pipeline they might be configured to measure per-image measurements only (in which case the message above is misleading): "If individual objects were measured, use an Export module to view their results".

Here is that list:
MeasureCorrelation
MeasureGranularity
MeasureTexture
CalculateMath

Extra credit to doublecheck my lists somehow in the code - I suspect one could do an exhaustive search for any module that saves per-object measurements.
