### ISSUE TITLE
simplifying the build process

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1403]
**Replacing Python Imaging Library (PIL)**

PIL complicates cross-platform installation (e.g. irregular releases to PyPI and mishandling dependencies). PIL is also responsible for a number of installation issues on GitHub and the message board (e.g. [broken FreeType header inclusion](http://stackoverflow.com/questions/20325473/error-installing-python-image-library-using-pip-on-mac-os-x-10-9)). Moreover, because PIL uses a representation that’s incompatible with NumPy’s `numpy.array`, expensive type conversions are frequently needed.

We should consider replacing PIL.

PIL is used for:

- [bit manipulation](https://github.com/CellProfiler/CellProfiler/blob/8b6d94bfedee683361dd467ea3708d1693118093/cellprofiler/cpmath/bg_compensate.py#L383-L404)
- [format conversion](https://github.com/CellProfiler/CellProfiler/blob/61075a2d6476760dcfda1abb63794b8f382242cc/cellprofiler/cpmath/haralick.py#L256)
- [reading images](https://github.com/CellProfiler/CellProfiler/blob/73797dea573e27cf441bf6ee0ad502bba42081d9/cellprofiler/cpmath/otsu.py#L322)

We could address most issues (e.g. a fix for the aforementioned FreeType issue) by using [Pillow](http://pillow.readthedocs.org) (“the friendly PIL fork”) rather than PIL. It’d be a painless transition (Pillow’s API is identical). However, it wouldn’t resolve our type conversion problems.

[scikit-image](http://scikit-image.org), another alternative, would resolve some of our type conversion problems since it uses NumPy’s `numpy.array` to store image data. However, it isn’t zero cost since it depends on Pillow (i.e. a one time cost). Moreover, some of our bit manipulation (e.g. color space conversion) can be replaced with methods from scikit-image.

Another option is using [ImageMagick](http://www.imagemagick.org/script/index.php) and a Python wrapper (e.g. [wand](http://docs.wand-py.org/en/0.4.0/)). ImageMagick is cross-platform and well-written. [OpenCV](http://opencv.org) is a similar option.

**Comment by LeeKamentsky** [comment]
CellProfiler itself uses python-bioformats to read and write images. If I remember correctly, Matplotlib needs PIL, so either PIL or Pillow has to be built in the makefile. I don't have any serious objection to switching to Pillow in the makefile (Makefile.CP2), other than the work of fixing whatever breaks when we make the switch. I believe that the Mac already uses Pillow instead of PIL.

Regarding the uses:

* [bit manipulation](https://github.com/CellProfiler/CellProfiler/blob/8b6d94bfedee683361dd467ea3708d1693118093/cellprofiler/cpmath/bg_compensate.py#L372) - the function bg_compensate is never used and could be removed.
* [format conversion](https://github.com/CellProfiler/CellProfiler/blob/61075a2d6476760dcfda1abb63794b8f382242cc/cellprofiler/cpmath/haralick.py#L252) is inside `if False` and can be removed
* [reading images](https://github.com/CellProfiler/CellProfiler/blob/73797dea573e27cf441bf6ee0ad502bba42081d9/cellprofiler/cpmath/otsu.py#L322) is test code that can be removed
* [writing images](https://github.com/CellProfiler/CellProfiler/blob/73797dea573e27cf441bf6ee0ad502bba42081d9/cellprofiler/modules/exporttodatabase.py#L1710) is probably the only place where PIL is necessary for CellProfiler functionality. We can change this code to write to a temporary file.

There is quite a bit of test code that still uses PIL. Not worth the effort of rewriting to use bioformats or other.

**Comment by 0x00B1** [comment]
Awesome. Helpful information! I’ll send a pull request for the Pillow modifications.

I’d also be happy to trim your PIL examples.

If you’re curious, I’m trying to improve the installation process. Ideally, I’d like:

```Bash
$ pip install cellprofiler
```

to work as expected!

**Comment by LeeKamentsky** [comment]
Go for it - I don't think that pull request would make it into 2.1.2, but the nonstandard installation is a longstanding problem (I think there's an issue for this somewhere). It may be more work than you anticipate.

Things to think about:
* Java integration - CellProfiler uses python-javabridge to run ImageJ and Bio-Formats and the installation uses Maven to assemble the .jar files it needs.
* Analysis worker - we probably need to switch to using an entry point to run the analysis worker process or alternately supply a command-line switch to CellProfiler to do so.
* Ilastik and other dependencies that don't have pip installers.

**Comment by 0x00B1** [comment]
> It may be more work than you anticipate.

:cry: :sob: :rage4:

I think it’s possible to do this piecemeal.

A few ideas about simplifying Java integration:

- extract `/imagej` into a separate repository and a new package on PyPI (i.e. python-bioformats).
- extract `org.cellprofiler.cellprofiler` into a separate repository and an artifact can be uploaded to a central Maven repository. 

I think this would also simplify continuous integration.

ilastik is a problem. Maybe I can convince @stuarteberg to accept a pull request that packages and releases on PyPI.

What are the other dependencies? I’m sure I’m missing a lot.

**Comment by LeeKamentsky** [comment]
Makefile.CP2 builds CellProfiler and its dependencies - I'd use it as the source for dependencies. A first cut might just bundle the .jar files as data files. You could finesse the issue with Ilastik temporarily by assuming that it has been installed - CellProfiler works without it.

**Comment by stuarteberg** [comment]
>Maybe I can convince @stuarteberg to accept a pull request that packages and releases on PyPI.

Some important points:

- IIUC, CellProfiler uses ilastik 0.5, which is no longer under active development.  ilastik 1.x has a radically different architecture and API.  @sommerc implemented support for using ilastik 1.x from within CellProfiler, but I don't know what remains to be done for it to be usable.  (I know there was an email thread between Anne Carpenter and Fred Hamprecht about this a couple months ago.)
- Unfortunately, we have no plans for packaging ilastik 1.x for PyPI.  At the moment, ilastik is built on Mac/Linux using a set of [custom-defined packages][1] for the conda tool.

[1]: https://github.com/ilastik/ilastik-build-conda

**Comment by 0x00B1** [comment]
Made some [progress](https://github.com/CellProfiler/CellProfiler/compare/master...0x00B1:features/setup.py). wxPython’s a challenge, but I have a few ideas.

**Comment by 0x00B1** [comment]
TIL: wxPython is the root of all evil.

**Comment by LeeKamentsky** [comment]
:smiling_imp: https://github.com/CellProfiler/CellProfiler/wiki/CellProfiler-roadmap#awaiting-new-software-engineer look at the third and fourth item (UI). Also look at https://github.com/LeeKamentsky/backend_swing . It's likely WX is not going to be a problem forever.

**Comment by 0x00B1** [comment]
Completed
