### ISSUE TITLE
Refactor imagej into a unique package 

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1454]
An ImageJ wrapper is broadly useful.

Let’s extract [our wrapper](https://github.com/CellProfiler/CellProfiler/tree/master/imagej) and release the package on PyPI.

**Comment by LeeKamentsky** [comment]
I'd want to postpone this one for a little bit or at least make it clear that the API is alpha and subject to change:
* Interface is messy and specific to CellProfler: interface should be made more generic and API usage should be clearer
* Wrappers were done before javabridge.JClassWrapper was written. Many of the wrapper classes should be eliminated and the code in run_imagej should use the wrappers directly.
* Lifecycle code in cpjvm should be moved into the package so that ImageJ can be started and disposed of uniformly by all users (Java threads persist if ImageJ is not disposed properly).
* ImageJ needs to be upgraded to current code base.
* How to package jars? Similar to python-bioformats (suggested jars, but user can override)?

But otherwise :+1:

**Comment by 0x00B1** [comment]
I don’t think any of the issues you raised should block a release with a:

'Development Status :: 3 - Alpha'

classifier. Hell, it might encourage some patches.

**Comment by 0x00B1** [comment]
https://github.com/CellProfiler/python-imagej/tree/features/packaging

**Comment by 0x00B1** [comment]
ImageJ support has been dropped.
