### ISSUE TITLE
re-architect module architecture

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1630]
A few opening questions:
- “Module” is problematic jargon since it has a precise meaning in software engineer and computer science. What’s an alternative?
- When should a user write a module?
- How should a module author layout their interface?
- Should we whitelist packages that are importable? What would we whitelist? NumPy? SciPy? OpenCV?
- What happens when a user runs a pipeline that calls missing modules?
- What happens when a user runs a pipeline that calls incompatible modules?
- Where do users find modules? Anne has talked about a public repository for modules.
- How do users install modules?

**Comment by 0x00B1** [comment]
[pluginbase](https://github.com/mitsuhiko/pluginbase) is a fantastic package from @mitsuhiko. It solves many of our present engineering problems. While it’s [used by](http://flask.pocoo.org/extensions) the author’s popular web framework, it hasn’t been updated since July, 2014. Likewise, [Flask Extension Development](http://flask.pocoo.org/docs/0.10/extensiondev/) is inspirational.

**Comment by 0x00B1** [comment]
> “Module” is problematic jargon since it has a precise meaning in software engineer and computer science. What’s an alternative?

A few suggestions from applications that share our [stream processing](https://en.wikipedia.org/wiki/Stream_processing) metaphor:

- [Automator](https://en.wikipedia.org/wiki/Automator_(software)) uses “action.”
- [Max](https://en.wikipedia.org/wiki/Max_(software)) uses “patch.”
- [Quartz Composer](https://en.wikipedia.org/wiki/Quartz_Composer#Compositions) uses “composition.”
- [Storm](https://en.wikipedia.org/wiki/Storm_(event_processor)) uses “bolt.”

**Comment by LeeKamentsky** [comment]
"Action" is pretty good. I think "Step" might be good, since that seems to have a link to experimental protocols (see http://vocab.linkeddata.es/SMARTProtocols/ and http://www.opmw.org/model/p-plan10112012/ for formal use of "step" in ontology). Also, steps are taken in sequence which is how a pipeline is presented (you don't take two steps in parallel and for better or worse, neither does CellProfiler).

In English, "My pipeline uses the IdentifyPrimaryObjects <insert term here> to segment the cells". 

"My pipeline uses the IdentifyPrimaryObjects step to segment the cells" 
"My pipeline uses the IdentifyPrimaryObjects action to segment the cells"
"My pipeline uses the IdentifyPrimaryObjects patch to segment the cells"
"My pipeline uses the IdentifyPrimaryObjects composition to segment the cells"
"My pipeline uses the IdentifyPrimaryObjects bolt to segment the cells"

**Comment by AnneCarpenter** [comment]
Are we literally talking about replacing the term "module" throughout
CellProfiler, from the user's perspective? If so, we would need to debate
this in a room all together, and fair warning, I might need to raise my
voice. (Hint: the answer is not going to be "bolt")  ☺

**Comment by dlogan** [comment]
And "module" is in dozens of publications. Which are difficult to refactor!

David
--
Sent from my phone.
Please excuse terse tappings.

**Comment by 0x00B1** [comment]
I’m offering a fresh perspective. :stuck_out_tongue: 

A CellProfiler module isn’t modular. Moreover, it masks a CellProfiler module’s most important characteristic: dataflow. A module’s position in a pipeline modifies its behavior.

Regardless, @AnneCarpenter @dlogan, any comments about the other items?

**Comment by AnneCarpenter** [comment]
Raising all these topics is great. I think we need to be in one room to
discuss; email too tedious. Special topics day, or coding day?

**Comment by braymp** [comment]
PE Harmony calls them "building blocks"
