### ISSUE TITLE
Morph question marks?

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1669]
In the Help for Morph, Branchpoints and Endpoints have question marks that are not described.  Should they be ones or zeros?
![image](https://cloud.githubusercontent.com/assets/1225595/10795655/2594abb0-7d71-11e5-9176-f16dfbc78b3d.png)

![image](https://cloud.githubusercontent.com/assets/1225595/10795660/2c4533f8-7d71-11e5-87e3-9d82b4d518d9.png)

**Comment by LeeKamentsky** [comment]
The question marks in the outputs are places where the values cannot be determined because they are on the border. For instance, the question mark on the upper left in "Branchpoints" might have no other foreground neighbors and not be a branchpoint, or it might have a foreground neighbor to the upper right and a neighbor to the lower left which would make it a branchpoint. Since we don't know, I entered "?" into the table.

**Comment by braymp** [comment]
Hmm, in those cases, what value does the operation actually output in CP?

**Comment by dlogan** [comment]
I had figured that was the answer, but regardless, what is the output of Morph?  Surely it's deterministic, and binary, no?

**Comment by LeeKamentsky** [comment]
I see the confusion - you're thinking that the left-hand side is the entire image, but I had only intended it to be a window. If it's the entire image, the output of Morph is deterministic. The image is padded with zeros for almost all operations (it's padded with 1 for hole filling, don't remember why), so it is deterministic and if it's needed, we can replace "?" with the correct answer.

**Comment by dlogan** [comment]
I see!  Yes, I assumed this was a tiny, but complete image.  I'd say either replace the "?" with the correct answer if it were a complete image, or just remove the "1"s from the border pixels in the left image to avoid confusion altogether. That leaves a small example, but they still make the illustration just fine I think.

**Comment by AnneCarpenter** [comment]
Propose to add this text for Branchpoints and Endpoints in the help:
"Note that shown here is a window into a hypothetical larger image; the “?” symbols reflect that in this small window those values cannot be calculated because the values necessary are outside the window. In reality, pixels at the border are handled by padding the image with zeros for almost all operations (except it is padded with 1 for hole filling)."
