### ISSUE TITLE
Suggestion to standardize column names

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1682]
This [Forum user](http://cellprofiler.org/forum/posting.php?mode=reply&f=17&t=4569#pr13868) suggests that the scheme of naming some modules' columns with a scale parameter appended (e.g. the '_3' in TrackObjects_DistanceTraveled_3) should be noted elsewhere, so that column names are standardized to make post hoc analyses not dependent on the scale(s) chosen.  This would affect other modules like MeasureObjectNeighbors and MeasureImageQuality, and change measurement names too which is painful.

**Comment by LeeKamentsky** [comment]
It's a problem. On the one hand, you want to be able to measure things at different scales and that means having different names for features that only differ by their scale. Maybe TrackObjects does not fit into that category, but MeasureObjectNeighbors almost certainly does need the scale because some user might want to use the module both ways in the same pipeline (expand to touching or expand by a fixed amount).

I think the long-term goal is to have richer feature metadata available - the goal of the narrow-db schema. That's not as user-friendly, but it solves the user's problem of wanting to pick out features at different levels of granularity (e.g. all shape features or all Texture_SumEntropy features measured on image X with objects Y regardless of scale).

The TrackObjects case is debatable. I have no problem taking it out. Want to make sure everyone approves before doing so.

**Comment by dlogan** [comment]
I was very hesitant in [my response](http://cellprofiler.org/forum/viewtopic.php?f=17&t=4569&p=13872#p13872) to the user.  I think it is fine to simply keep this in mind for the future when we maybe do switch to a different db schema, narrow or otherwise.

**Comment by AnneCarpenter** [comment]
I'd vote that the scale should stay as-is even though I admit we are likely
not consistent in this approach: there are probably other modules where a
person might want to run the module with multiple settings and the only way
to get different column labels is a workaround where you identify the same
objects twice and give them different names each time (rather than having
some settings incorporated in the column name, as TrackObjects does).
Still, it seems simple enough to adapt downstream customized code to deal
with the change in the case where a researcher wants to ignore the
difference. I think I will close the issue, but anyone is welcome to
re-open and counter-argue the case!
