### ISSUE TITLE
Create new folder icon does not gray out after using it

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1692]
On Dev Mac at least, click View Output settings.  Click the 'create new folder' icon in Default Output Folder setting, and name a new folder.  This works, but I expected the icon to gray out but it doesn't.
Though the above Default Input Folder's counterpart *is* grayed out?
![image](https://cloud.githubusercontent.com/assets/1225595/11000788/ae5274bc-8471-11e5-8ab3-0e8f3da79358.png)

**Comment by LeeKamentsky** [comment]
On the PC, many buttons show up as disabled as well, although they are not. Here, I pressed "Run" and got this display:
![image](https://cloud.githubusercontent.com/assets/660469/11001094/6c50924a-8473-11e5-8c04-df0d94baf7ce.png)

**Comment by dlogan** [comment]
I just clicked Run in Test Mode on Mac, and it looks fine 
![image](https://cloud.githubusercontent.com/assets/1225595/11001517/82dd1496-8475-11e5-80b1-482ba8a07bbd.png)

Side note: the "Next Image Set" button should be grayed out since I have only one image set.

**Comment by AnneCarpenter** [comment]
I think that CP's current behavior is correct for the specific case described first in the post - just because you've created a new folder already doesn't mean you might not want to create another new one, right? So I think we should not fix the originally reported issue.

The post is a little confusing as to the other button behavior observed vs expected, so if you're still seeing problems please create new issues.
