### ISSUE TITLE
Add Kirsch filter to EnhanceEdges

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1714]
A CP workshop attendee suggested the the [Kirsch filter](https://en.wikipedia.org/wiki/Kirsch_operator) works well for pre-processing his brightfield images for segmentation. Might be worth adding.

**Comment by LeeKamentsky** [comment]
@0x00B1 - This one is a real easy win and would be a lot of fun to do. Do you want to work on it together? The article is here (local link on file system to copyrighted article: /imaging/cold/People/Lee/issues/issue1714/Kirsch.pdf, doi: http://dx.doi.org/10.1016/0010-4809(71)90034-6, url: http://www.sciencedirect.com/science/article/pii/0010480971900346) It's from 1970, a real hoot because the images the author processes are rendered in ASCII with the intensities represented by characters with different densities, e.g: https://gist.github.com/LeeKamentsky/bceca83c1236ab37f426

**Comment by 0x00B1** [comment]
@LeeKamentsky Sure! I’ll read the paper now.

**Comment by 0x00B1** [comment]
I sketched out an implementation: https://gist.github.com/0x00B1/7572ad7a50453eabb32c

**Comment by 0x00B1** [comment]
Helpful notes (pp. 46) https://ece.uwaterloo.ca/~ece327/course-notes/lab-manual.pdf

**Comment by 0x00B1** [comment]
https://github.com/CellProfiler/centrosome/pull/47

**Comment by dlogan** [comment]
Nice!  I will try this on an edge detection problem I have soon.

Though as [this PPT](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjB5ZLD_a3JAhWC8CYKHbKnAsEQFggqMAM&url=http%3A%2F%2Fpublic.callutheran.edu%2F~reinhart%2FBIEN482Imaging%2FWeek06%2FEdgeDetection.ppt&usg=AFQjCNHT7QxoM0NBN4aIreEQc8zBsFxYxQ&sig2=vrTKgg28KCpIDrY9biDAyw) points out on slide 32, one need only calculate half of the directions' convolutions, as the other half are merely sign changes.  As I look at the code, it does seem to do 8 convolution steps.  I don't know how much a difference it will make computationally, but ponder taking advantage of this trick.

**Comment by LeeKamentsky** [comment]
Initially, I thought it was a clever trick, but on a second reading, I am not so sure. The kernel is not symmetric and, although kernel N will always have the opposite sign of kernel N+4 mod 8, the magnitudes will be different (but we should verify). The speedup is not such a big deal - the code is pretty fast in the context of CP (compare to Canny, for instance).
