### ISSUE TITLE
CorrectIlluminationCalculate: Implement resize for speed improvement

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#1731]
We have found that downsampling the incoming images does not adversely affect the final ICF if aggregating across a lot of images. It may be worth adding this as an option.

We would need to:
* Downsample the input image by some user-provided fraction/percentage.
* Reduce the smoothing filter size(s) by the proportional amount
* Upsample the final aggregated ICF by the inverse fraction/pct for use.

**Comment by AnneCarpenter** [comment]
The default (that is, auto-calculated) amount of downsampling should be proportional to the smoothing filter size, because that gives a sense of what amount of information ‘loss’ the user is willing to tolerate/aiming at. That is, it shouldn’t be calculated as a fraction of the original image because the image dimensions tell us nothing of the dimensions of the illumination pattern or structures of interest in the image.

**Comment by LeeKamentsky** [comment]
Good point - we can add a downsampling option and if that's selected, an automatic / manual option. There's not much point reducing an image from 2K x 2K to 64 x 64 for a ginormous smoothing size, but  we can use some heuristic that compromises between smoothing size and image size and give the user an override.

**Comment by AnneCarpenter** [comment]
Is a workaround to build a pipeline that does the resizing before and after IllumCorrection? Regardless, setting this for future consideration.
