### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_relationship_groups'

### ISSUE THREAD

**Issue by jhung0** [CellProfiler/CellProfiler#1745]
I'm getting this error at different stages (like after 1 image processed, after 3, after 52) and can't tell what the issue is:

Traceback (most recent call last):
  File "/Users/jyhung/Documents/CellProfiler/cellprofiler/utilities/thread_excepthook.py", line 25, in run_with_except_hook
    run_old(*args, **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jyhung/Documents/CellProfiler/cellprofiler/analysis.py", line 441, in interface
    self.copy_recieved_measurements(recd_measurements, measurements, image_numbers)
  File "/Users/jyhung/Documents/CellProfiler/cellprofiler/analysis.py", line 521, in copy_recieved_measurements
    measurements.copy_relationships(recd_measurements)
  File "/Users/jyhung/Documents/CellProfiler/cellprofiler/measurements.py", line 781, in copy_relationships
    for rk in src.get_relationship_groups():
AttributeError: 'NoneType' object has no attribute 'get_relationship_groups'

**Comment by LeeKamentsky** [comment]
It looks like there's some problem opening an HDF5 file. There's probably a line in the log output like "Error loading HDF5 <filename>.hdf5". It's somewhat perplexing how you'd get into that situation and unfortunately, the actual error is a little hidden from us. I think the best thing for me to do is see if I can recreate it in an environment as close as possible to yours.

Could you do "pip freeze" and post the results and I'll try to set up something on my Mac that can replicate.

**Comment by jhung0** [comment]
The weird thing is that everything worked when I was back at the Broad.
This error happened when I was at home using VPN.

**Comment by LeeKamentsky** [comment]
It's possible that CellProfiler was using a folder that was not accessible over the network when you were at home. The default output folder is used for the temporary file that's used for the communication. If you were in a situation where there would be intermittent errors caused by failure to read files, you'd see that kind of an error.

The code here: https://github.com/CellProfiler/CellProfiler/blob/9465155067bdcb8ffe5d70170877f110c13a75f2/cellprofiler/measurements.py#L1863 swallows the exception and returns None and I believe that's causing your problem. I think it's a bug to handle that exception and have that cause an unrelated error further on, but my change would be not to handle the exception and have the user see a more informative error (but CellProfiler would fail in the same places).
