### ISSUE TITLE
Fixed Scale in Color coded plots in DisplayDataOnImage

### ISSUE THREAD

**Issue by mrohban** [CellProfiler/CellProfiler#1762]
It would be helpful if the user could specify the scale of the color-coded plot in this module, especially for the purpose of comparing two images head-to-head. Here is the module details in the pipeline I used:
![screen shot 2016-01-21 at 12 03 07 pm](https://cloud.githubusercontent.com/assets/11319440/12487863/090b655c-c037-11e5-90bd-6bcf8de449c5.png)
In the next two images, the color scale is set automatically by CP, which makes the comparison between the two images visually difficult:

[Empty_41744_Cells_Texture_Correlation_PhGolgi_3_0.pdf](https://github.com/CellProfiler/CellProfiler/files/99515/Empty_41744_Cells_Texture_Correlation_PhGolgi_3_0.pdf)
[AKT3_WT2_41744_Cells_Texture_Correlation_PhGolgi_3_0.pdf](https://github.com/CellProfiler/CellProfiler/files/99516/AKT3_WT2_41744_Cells_Texture_Correlation_PhGolgi_3_0.pdf)

**Comment by LeeKamentsky** [comment]
Hi Mohammed,
I just took a look at this - I am guessing that you are running 2.1.1. It was fixed by this: https://github.com/CellProfiler/CellProfiler/commit/ce2092112717220af84d911f906657e34d0a485f
and the request is a duplicate of issue #1269.

Let me know if that's what you want - Allen and I will probably have binaries for people to test on coding day if you want to try. If it's fixed, please close.

--Lee

**Comment by mrohban** [comment]
Thanks, it works.
