### ISSUE TITLE
EnhanceOrSuppressObjects -> Speckles can produce values < 0

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1834]
Run zipped pipeline with the image provided (I ran Mac 2.2.0rc3).
[lysosomes_structures_DLogan.cppipe.zip](https://github.com/CellProfiler/CellProfiler/files/167535/lysosomes_structures_DLogan.cppipe.zip)
![8b8af277acc313079835cefd8f2cb0c6f5232ab1](https://cloud.githubusercontent.com/assets/1225595/13675859/7fef25f0-e6b1-11e5-9270-ce3f4d053e87.png)

EnhanceOrSuppressFeatures looked odd in Image Contrast = Normalized mode, but it turns out that it is because (I think) the lowest intensity values are < 0. I think they should be [0,1] valued.

![image](https://cloud.githubusercontent.com/assets/1225595/13675932/c09b9fac-e6b1-11e5-9aa9-3ffbb333a6d3.png)

Zoomed in, you can see some darker, < 0 value pixels:
![image](https://cloud.githubusercontent.com/assets/1225595/13675987/f866c600-e6b1-11e5-8254-df6eb2babefc.png)

**Comment by LeeKamentsky** [comment]
You're right. The fast method has a radius of .5 as input. I think the lower limit on the median filter is around 3 because it needs to make a hexagonal shape and there just  aren't enough pixels. If you use the slow/circular option, it doesn't do anything because the radius is .5. You need to increase the feature size to 3 (one pixel to the left, one pixel above, one pixel below and one to the right) or you will get a blank image.

I will fix it so that it runs the "slow" method if the radius is unreasonably small. It will actually run faster than fast for that size.

**Comment by dlogan** [comment]
:+1:

**Comment by dlogan** [comment]
Thanks!  But on retesting, I discovered another issue which may have been pre-existing, not sure. If the  speckle Feature Size = 2, then the output image is all zeros.  Regardless of the Fast/Slow setting. Maybe the settings.

![image](https://cloud.githubusercontent.com/assets/1225595/13683500/fd02ff44-e6d4-11e5-9c1b-d2caba8241e1.png)

Should the min size just be set to 3 here?
https://github.com/CellProfiler/CellProfiler/blob/6cf9b7c85fddf3b71c5f165e8d9feb607673043e/cellprofiler/modules/enhanceorsuppressfeatures.py#L118

**Comment by LeeKamentsky** [comment]
Arguably yes, it should be 3 unless someone wants a blank image on purpose. I will make it so.
