### ISSUE TITLE
Remove “File name regular expression guesses” option

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#1942]

**Comment by LeeKamentsky** [comment]
this option is part of a user-requested feature that lets users have site-specific guesses

**Comment by braymp** [comment]
I'd put a "yellow" light on this one, since our rationale was the following:
* Regexs are a powerful means of acquiring needed metadata from files/folders...
* ...But we've learned over time that we can't anticipate all cases, and new ones keep showing up.
* So let the user add their own as needed.
We couldn't think of a better place to put it, so we put it here. I think the functionality should remain, but the location is certainly up for grabs.

**Comment by 0x00B1** [comment]
I gave you an expanded notes box and a white background for the file chooser and this is how you repay me? 😝

**Comment by mcquin** [comment]
@braymp If you'd like this feature added back, please open a separate issue.

**Comment by mcquin** [comment]
@braymp Please ignore last message. I misunderstood.
