### ISSUE TITLE
Measure Length tool is laggy

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler#1998]
The figure window Tools menu > "Measure Length" is a little more laggy than I'd expect.  See this video: http://cl.ly/1s201x421c0i

There seem to be some extra refreshes in the table on the lower-right during the arrow updates which might be an issue.

**Comment by 0x00B1** [comment]
Yep

But the problem isn’t isolated to “Measure Length—” the figure window has major performance problems.

**Comment by 0x00B1** [comment]
I wish this were an easy fix, unfortuantly:

* cpfigure.py is 2195 LOC
* CPFigureFrame has over 500 fields, methods, and sub-classes (!!!)
* controller, model, and view are wholly coupled
* there’s 0 tests for the cellprofiler.gui.cpfigure module

TLDR: It needs a major refector. :)

**Comment by 0x00B1** [comment]
CPFigureFrame does way too much, e.g.

<img width="640" alt="measuretexture__13__image_cycle__1" src="https://cloud.githubusercontent.com/assets/315821/14943780/ebde7140-0faf-11e6-9553-d92fc359c8c3.png">

<img width="640" alt="saveimages__15__image_cycle__1" src="https://cloud.githubusercontent.com/assets/315821/14943774/c1803c12-0faf-11e6-9c09-3b0e245443fa.png">

**Comment by 0x00B1** [comment]
I still don’t understand the purpose of CPFigure. Why don’t we just dump everything into a directory with the appropriate file extension? Let people use their preferred tools that are likely more usable.

**Comment by braymp** [comment]
Arguably, the workspace viewer deprecates some of these issues. However, I would also argue the following:
* Re: measurements shown n the window - I've not been a huge fan of this, but at times I find it helpful to see if the results for a given image are reasonable short of a full run. 
* I would prefer to have the visual display/feedback and the CP UI coupled. I'd rather not have to navigate to some folder and use yet another tool to do to figure out if I'm getting close to the right answer. E.g., to estimate length in an image, it's not obvious what software I would use to do this otherwise.

**Comment by dlogan** [comment]
Yeah, I'd really prefer to have an integrated window(s).  My preference would be for some single window, like Workspace Viewer as a valiant first attempt.  Somewhere on the Roadmap there are other thoughts, no?  Other things to keep:
* Synced displays within a window for zooming
* Context menus with lots of nice image analysis related features 
* Normalized intensity views
* etc

**Comment by 0x00B1** [comment]
What’s the Workspace Viewer?

**Comment by braymp** [comment]
It shows some of the image/object/measurement features combined into one display. To try it:
* Load the welcome screen pipeline
* Enter test mode
* Press the viewer button at the bottom right, and check out the panel that appears.

**Comment by 0x00B1** [comment]
Wow. I’ve never seen this. And, frankly, I’m not sure what it’s supposed to do. 😳

**Comment by braymp** [comment]
I notice that the workspace viewer was removed. Is it going someplace else in the UI? I consider it an extremely useful tool for IAD, with a substantial time investment by Lee, David and I to get it going.

**Comment by 0x00B1** [comment]
Yep

**Comment by 0x00B1** [comment]
And I appreciate the work. However, we're focused on UI cleanup for funding purposes. Unfortunately, Workspace Viewer complicates that and needs some serious polish.

**Comment by 0x00B1** [comment]
@braymp it would help if you could share some of your favorite features of Workspace Viewer. Likewise, some of the features you don't use and whatever features you'd really like!

**Comment by dlogan** [comment]
@0x00B1 Does this

> Yep, but it will be hidden behind a feature flag.

mean that there is a flag now to access workspace viewer?  Or will be?  

It would seem prudent that we keep a functionality until we have test branch that has any sort of replacement if folks find it useful.

This is an example of on-the-fly overlaying which is much easier in Workspace Viewer than adding multiple OverlayOutline modules, as well as DisplayDataOnImages, etc:
https://github.com/CellProfiler/CellProfiler/issues/1789#issuecomment-202502083

**Comment by 0x00B1** [comment]
> This is an example of on-the-fly overlaying which is much easier in Workspace Viewer than adding multiple OverlayOutline modules, as well as DisplayDataOnImages, etc: #1789 (comment)

Nice

**Comment by 0x00B1** [comment]
> It would seem prudent that we keep a functionality until we have test branch that has any sort of replacement if folks find it useful.

For sure. But even for nightly?

**Comment by dlogan** [comment]
No, of course nightly is ok to expect features to change.  But in 6 weeks it turns into a Beta pumpkin! Maybe in 12 weeks we'd have a replacement?  Or Workspace Viewer fans would just live with older versions.

**Comment by braymp** [comment]
Sure!

The display figures have been a mainstay of CP since the beginning but are
plagued by some issues users have pointed out over the years:

   - If a pipeline is long, that's a lot of windows.
   - Figures for the measurement modules don't make a lot of sense, and I
   have to explain that for the per-object measurement modules, what is shown
   is a summary, not just a single measurement for only one object.
   - If users pick a zoomed-in view, that zoom is lost when the module is
   re-evaluated in test mode.
   - If performing IAD across several objects, not being able to see the
   object segmentation in context to each other can hamper efforts.

The workspace viewer deals with each of these:

   - It functions as a "one-window-to-hold-them-all" panel. Combinations of
   images, objects and measurements can be displayed/updated together.
   - User-selected views are maintained when the pipeline is adjusted.
   - It also updates in real-time: in test mode, if you skip to the next
   image set, you can see the elements update as the pipeline executes,
   providing some helpful visual feedback.

My hope was to have the 2.2.0 release sometime before my last workshop b/c
I wanted to incorporate it into my slidedeck; there are several elements
which make the presentation/demo easier. It didn't happen, but I was
looking forward to having it out there regardless, even if not publicized
as much as I would like.
