### ISSUE TITLE
Remove `jvm-heap-size` command-line option

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#2048]

**Comment by braymp** [comment]
Is the memory allocated to the JVM no longer an issue? Because having this flag is critical for being able to load large image sets; see #787, http://forum.cellprofiler.org/t/cannot-load-large-images-java-heap-space-error/1632, and http://forum.cellprofiler.org/t/java-exception-on-pressing-update-inside-metadata-module/2362 for a few examples.

**Comment by 0x00B1** [comment]
Unfortunately, it’s still an issue. You should use:

```bash
set JAVA_OPTS="-Xms128m -Xmx256m"
```

rather than `--jvm-heap-size`. For example:

```bash
JAVA_OPTS="-Xmx256m" cellprofiler
```

**Comment by braymp** [comment]
Probably good to document somewhere then. It's almost certain to come up at
some point.
