### ISSUE TITLE
ExportToSpreadsheet creates erroneous perImage CSV in thumbnail columns

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2242]
I have a pipeline where ExportToSpreadsheet and ExportToDatabase are both used. ExportToDatabase is configured to export thumbnails. When viewing the "perImage" table created by ExportToSpreadsheet there are columns are created for each thumbnail. The spreadsheet is then "unparsable", because it looks like a image is written into the CSV, manifested as a long list of random characters.

Should there be a column for thumbnails at all? It seems like ExportToSpreadsheet is exporting the perImage table stored in the SQLite database, which is apparently incompatible with CSV.

**Comment by braymp** [comment]
I've come across this before. The workaround is to go to ExportToSpreadsheet, select the cols you want to save, and exclude only the thumbnail cols. Alternately, if you import the file in Excel (so that you use the import wizard), rather than open it outright, I think it will do the right thing (since the thumbnails should have dbl-quotes) 

I'm on the fence re: whether the thumbnail cols should be there or not. My thinking is that when ExportToSpreadsheet and ExportToDB are eventually unified, it should be OK to have them. But I do wonder whether they're more trouble than their worth in a CSV..

**Comment by AnneCarpenter** [comment]
Given there is a workaround, let's close and mark this for future consideration.
