### ISSUE TITLE
Filtered-out primary objects prevent secondary objects from fully propagating

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2290]
From [this post](http://forum.cellprofiler.org/t/identifysecondaryobjects-propagation-bug/3870):
User couldn't figure out why sometimes when his cells were close to the edge IDSecondary using "propagate" seemed to arbitrarily cut off pretty far from the edge of the cell.  It turns out it was due to some nuclei that had been filtered out in IDPrimary for touching the border; when I turned the regularization factor down to 0 it filled the whole cell except for the area where the nuclei had been.  

I can't think of a reason why IdentifySecondary would want to respect objects that never truly existed in the first place in making its calculations of where to regularize the border but 
a) It's Friday afternoon so maybe there are good reasons and I just can't think of them 
b) I expect there's something going on under the hood (are filtered out objects treated as masks or something?) that probably both explains this behavior and makes it hard to avoid.

**Comment by braymp** [comment]
> I can't think of a reason why IdentifySecondary would want to respect objects that never truly existed in the first place

Oh, yes you do :smile:

I don't have an instance on me right now, but think of it this way: the secondary cell really is there but you've chosen to filter it out since the nucleus touched a border. If a neighboring secondary object ignored the missing cell, it would simply fill in that space, and he boundaries would no longer look the way you'd expect, i.e, respecting the boundaries of the neighbors. Rather, it would (most likely) look like two cells incorrectly merged together.

**Comment by bethac07** [comment]
I said I couldn't think of one, not that I was certain one did not exist :smile: .  Hence why I wanted to expose it to the wisdom of the hivemind.  Will close.
