### ISSUE TITLE
Page with instructions for installing on CentOS no longer exists

### ISSUE THREAD

**Issue by jacksonofalltrades** [CellProfiler/CellProfiler#2383]
This link is broken.
http://cellprofiler.org/linux.html

I need to install this on CentOS, please advise?

**Comment by 0x00b1** [comment]
@jacksonofalltrades We removed the page because it was very outdated. Thankfully, the instructions are not too complicated:

- Install the Java Development Kit (JDK)
- Install Python
- Install Cython, matplotlib, NumPy, and SciPy with pip
- Clone the CellProfiler repository
- Run `pip install -e .` from the CellProfiler directory

**Comment by AnneCarpenter** [comment]
@0x00b1 Thanks, Allen - do you want me to paste those instructions on this page: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28Linux%29

They would replace these instructions: 
"Unless you need the Developer's Version of CellProfiler, the easiest way to get CellProfiler running on CentOS 6 is to install the compiled version with yum. Instructions can be found here: http://cellprofiler.org/linux.html  There are currently no instructions how to install on CentOS 6 from source."

Happy to do it, LMK!

**Comment by jacksonofalltrades** [comment]
Thank you so much, I got this to work!

-Dave

**Comment by AnneCarpenter** [comment]
@0x00b1 Allen, please answer "do you want me to...." question.

**Comment by mcquin** [comment]
Updated the Wiki page with the high level instructions.
