### ISSUE TITLE
MeasureTexture should support three-dimensional images

### ISSUE THREAD

**Issue by 0x00b1** [CellProfiler/CellProfiler#2454]

**Comment by mcquin** [comment]
Should MeasureTexture support 3D Gabor features?

**Comment by braymp** [comment]
I guess you could; I can imagine certain assays where it would useful. But two issues come to mind:
* How to specify the # of angles in 3D?
* Since the operation is computationally heavy (IIRC) and the usefulness if iffy (IHMO), if you implement it, the ``Measure Gabor features?`` default should be "No"

**Comment by AnneCarpenter** [comment]
One approach: leave it out and see if anyone complains.
