### ISSUE TITLE
Add 'normalize well padding' option to Metadata module

### ISSUE THREAD

**Issue by nieder** [CellProfiler/CellProfiler#2685]
From this [forum post](http://forum.cellprofiler.org/t/method-to-pad-the-metadata-well-number/4033):

When the input images are named so: `A - 7(fld 1 wv UV - DAPI).tif`, the Metadata module is able to parse all the relevant bits (row, col, field, filters). But the Metadata_Well column in my output ends up looking like this:

````
A1
A10
A11
A12
A2
A3
A4
A5
A6
````

Which makes it very annoying to have to resort afterwards outside of CellProfiler. A suggested fix would be to add a checkbox (or toggle) in the Metadata module to normalize Well ID padding.

Possible Solution 1: checkbox that when activated makes sure all the wells have the same number of digits as the largest value (eg, A3 and A12 become A03 and A12). This change may also need to be applied to the Column metadata property (but then it would change from integer to string).
Possible Solution 2: pulldown menu or radio buttons that lets you select whether to add or remove leading zeros in the numerical part of the Well metadata. If "add leading zeros" is selected, then Well (and Column?) metadata are padded to have leading zeros as needed to normalize the length. If "remove leading zeros" is selected, then any leading zeros would be removed (A03 -> A3).

**Comment by zindy** [comment]
Maybe a checkbox to use "natural sorting" as per first answer to this stackoverflow question: http://stackoverflow.com/questions/4836710/does-python-have-a-built-in-function-for-string-natural-sort

```
>>> from natsort import natsorted, ns
>>> x = ['Elm11', 'Elm12', 'Elm2', 'elm0', 'elm1', 'elm10', 'elm13', 'elm9']
>>> natsorted(x, key=lambda y: y.lower())
['elm0', 'elm1', 'Elm2', 'elm9', 'elm10', 'Elm11', 'Elm12', 'elm13']
>>> natsorted(x, alg=ns.IGNORECASE)  # or alg=ns.IC
['elm0', 'elm1', 'Elm2', 'elm9', 'elm10', 'Elm11', 'Elm12', 'elm13']
```

**Comment by nieder** [comment]
Good catch. Natural sorting would also be a possible solution. It keeps the original values intact but solves the underlying issue of having A11 before A2.

**Comment by braymp** [comment]
This would be great esp. when using the image/group set selection dialog in Test mode, since the default alphabetical sorting makes searching for the desired well-based metadata a pain.

**Comment by braymp** [comment]
Same is also true for proper ordering of time-lapse movies when the frame number is captured as metadata.

**Comment by zindy** [comment]
I was able to confirm that we may be able to natsort the filenames directly, even with multiple fields (as per Mark's suggestion, well name + timepoint in the same filename).

Some simple code to generate empty files and try natsort:
```
import os
from natsort import natsorted

def id_to_well(nx,ny,x):
    return "%c%d"%(chr(65+x/nx),x%nx+1)

#100 timepoints, 6 wells
n_tp = 20
nx = 12
ny = 8
n_wells = nx*ny
directory = r"D:\temp"

# ^test_w(?P<Well>.*)_t(?P<Timepoint>.*)\.tif
def genfiles():
    l = []
    for t in range(n_tp):
        for w in range(n_wells):
            fn = "test_w%s_t%d.tif" % (id_to_well(nx,ny,w),t)
            l.append(fn)

    return l

if __name__ == '__main__':
    l = genfiles()
    ll = natsorted(l)
    print len(l)
    print len(ll)
    print ll

    if 0:
        for fn in l:
            fn = os.path.join(directory,fn)
            f = open(fn,"w")
            f.close()
```

The regexp for the metadata is ```^test_w(?P<Well>.*)_t(?P<Timepoint>.*)\.tif```

The natsorted file list looks like:
```
['test_wA1_t0.tif', 'test_wA1_t1.tif', 'test_wA1_t2.tif', 'test_wA1_t3.tif', 'te
st_wA1_t4.tif', 'test_wA1_t5.tif', 'test_wA1_t6.tif', 'test_wA1_t7.tif', 'test_w
A1_t8.tif', 'test_wA1_t9.tif', 'test_wA1_t10.tif', 'test_wA1_t11.tif', 'test_wA1
_t12.tif', 'test_wA1_t13.tif', 'test_wA1_t14.tif', 'test_wA1_t15.tif', 'test_wA1
_t16.tif', 'test_wA1_t17.tif', 'test_wA1_t18.tif', 'test_wA1_t19.tif', 'test_wA2
_t0.tif', 'test_wA2_t1.tif', 'test_wA2_t2.tif', 'test_wA2_t3.tif', 'test_wA2_t4.
tif', 'test_wA2_t5.tif', 'test_wA2_t6.tif', 'test_wA2_t7.tif', 'test_wA2_t8.tif'
, 'test_wA2_t9.tif', 'test_wA2_t10.tif', 'test_wA2_t11.tif', 'test_wA2_t12.tif',
 'test_wA2_t13.tif', 'test_wA2_t14.tif', 'test_wA2_t15.tif', 'test_wA2_t16.tif',
 'test_wA2_t17.tif', 'test_wA2_t18.tif', 'test_wA2_t19.tif', 'test_wA3_t0.tif',
'test_wA3_t1.tif', 'test_wA3_t2.tif', 'test_wA3_t3.tif', 'test_wA3_t4.tif', 'tes
t_wA3_t5.tif', 'test_wA3_t6.tif', 'test_wA3_t7.tif', 'test_wA3_t8.tif', 'test_wA
3_t9.tif', 'test_wA3_t10.tif', 'test_wA3_t11.tif', 'test_wA3_t12.tif', 'test_wA3
_t13.tif', 'test_wA3_t14.tif', 'test_wA3_t15.tif', 'test_wA3_t16.tif', 'test_wA3
_t17.tif', 'test_wA3_t18.tif', 'test_wA3_t19.tif', 'test_wA4_t0.tif', 'test_wA4_
t1.tif', 'test_wA4_t2.tif', 'test_wA4_t3.tif', 'test_wA4_t4.tif', 'test_wA4_t5.t
if', 'test_wA4_t6.tif', 'test_wA4_t7.tif', 'test_wA4_t8.tif', 'test_wA4_t9.tif',
 'test_wA4_t10.tif', 'test_wA4_t11.tif', 'test_wA4_t12.tif', 'test_wA4_t13.tif',
 'test_wA4_t14.tif', 'test_wA4_t15.tif', 'test_wA4_t16.tif', 'test_wA4_t17.tif',
 'test_wA4_t18.tif', 'test_wA4_t19.tif', 'test_wA5_t0.tif', 'test_wA5_t1.tif', '
test_wA5_t2.tif', 'test_wA5_t3.tif', 'test_wA5_t4.tif', 'test_wA5_t5.tif', 'test
_wA5_t6.tif', 'test_wA5_t7.tif', 'test_wA5_t8.tif', 'test_wA5_t9.tif', 'test_wA5
_t10.tif', 'test_wA5_t11.tif', 'test_wA5_t12.tif', 'test_wA5_t13.tif', 'test_wA5
```
You can clearly see that the wells are ordered in increasing order through A1, A2, ... as well as through the correct timepoints t0, t1, t2 ...

So is the answer to natsort the list of files between the "Images" and "Metadata" step? Maybe in modules\loadimages.py? Sorry, didn't get that far.

Kind regards,
Egor

**Comment by braymp** [comment]
My guess is that NamesAndTypes is the proper place, since that's where the image sets are actually created/displayed. It might be nice to have it in the Metadata module, but it's probably not essential since it's more for display there than anything else.

I also wonder whether such a thing should be active by default, since I have trouble an instance where it *wouldn't* be appropriate or would break something.

**Comment by karhohs** [comment]
### Sorting is good
I agree with @braymp @zindy and @nieder that this behavior would be convenient, intuitive, and perhaps event the default behavior. I imagine updating Metadata or NamesAndTypes could be a challenge, because of a Java VM that enters the mix via javabridge and is involved with parsing file names.

A natural place to update the default behavior would be the Metadata module where after you set the *Metatdata data type* drop down to *Choose for each*. Then the specific data type can be set. Using @zindy regexp this would mean changing *Timepoint* to Integer (See below image). Once the extracted metadata becomes an integer, sorting via numpy should be possible; I'm imagining the metadata would be stored in a pandas table.

![metadata_integer](https://cloud.githubusercontent.com/assets/156232/24878069/96852806-1dff-11e7-80c0-b16b7c36460e.png)

### While we're waiting
However, while waiting for a CP solution, it might be expedient to rename the images themselves before using CellProfiler to get the ordering you want. [This stackoverflow post](http://stackoverflow.com/questions/2759067/rename-files-in-python) has a python solution for doing this task. Also, here is an example on how to add padding to a string in python: `new_filename = "test_w{0}_t{1:0>2}.tif".format(wellname, timepoint)`. e.g. `"test_w{0}_t{1:0>2}.tif".format("A4", 1)` becomes `test_wA4_t01.tif`.

### Data to play with
I wanted to make sure that the incorrect ordering shown by Metadata and NamesAndTypes wasn't corrected downstream by the TrackObjects. Therefore I made some fake data that looks like @zindy example filenames. I am attaching this files and a pipeline, below, in case someone working on this issue might find it useful.

[test_images.zip](https://github.com/CellProfiler/CellProfiler/files/911263/test_images.zip)

**Comment by zindy** [comment]
@karhohs Thank you for checking my image set.

Just an aside, the reason why my set is a lot larger is that it's kind of a worse case scenario which involves *both* unpadded well names (A1 to H12) and unpadded timepoints (t0 to t19).

What I found surprising when using the natsort library, is that it was able to take care of both problems simultaneously. This is why in my mind, natsort should be applied after the "Images" step (filenames are known) and before the "Metadata" step. I know, easier said than done!

I did try to add natural sorting in various modules today. Being able to reload modules from the Test menu is of great help for that! But so far, I haven't been successful.

Cheers,
Egor

**Comment by karhohs** [comment]
@zindy This question is more for my curiosity than anything else... I see how the order of processing time points is crucial to a tracking problem, but I do not see the same importance for processing a plate of data in a certain order. Would you please give an example?

**Comment by braymp** [comment]
One UI-related instance is when selecting an image in Test mode, if the listing follows an alphabetical rather than natural sort, it gets v. tedious to search for the well of choice if the numbering jumps from '1' to '10' and later back to '2'.

**Comment by nieder** [comment]
@karhohs: for well order, besides @braymp said, having the output csv files sorted in a natural way is also useful if the results need to be further processed for downstream usage (eg moving columnar data into matrix format). The processing order might not be important, but the output order very well may be.

It's a lot easier to convert this into a matrix
~~~~
A1
A2
A12
B1
B2
B12
~~~~
than this:
~~~~
A1
A12
A2
B1
B12
B2
~~~~
It's also just easier for a person to scan results.

**Comment by zindy** [comment]
@karhohs, you're right, it's for convenience mostly, but all the equipment I can think of homes to A1.

So that's the well you might use for testing your image acquisition and then for testing assays in CellProfiler. So it makes sense to design/test/tweak your assay for A1 as well. For now, I just use a rule on the filename to reduce the imageset to a particular well for testing.

If you only look at platemaps, I agree, it doesn't matter which order the wells are processed in (processed not acquired).

**Comment by karhohs** [comment]
I just wanted to echo that the "easiest" fix, i.e. no changes to CellProfiler required, is to do one or a combination of the following:

1. Change the filenames, and add number padding, before importing them into CellProfiler.
1. Create a metadata CSV with at least two columns. One is *filename* and the other is *timepoint*, others could be *wellname* etc. Instead of using regexp to parse metadata, use this CSV and the *Import from file* extraction method in the Metadata module.
1. Let CellProfiler process the data in its preferred order and then sort the output data as part of the analysis or post-processing. R can do this easily and so can Python with Pandas, or even Matlab using the Tables datatype.

**Comment by mcquin** [comment]
I support the suggestions @karhohs has made. If you would like your files sorted in a way that is not consistent with lexicographic order (the sorting algorithm of computers), it would be best to do that as a pre-processing step outside CellProfiler.

**Comment by nieder** [comment]
Changing the file name modifies the original data. That is a no-go in many situations where data constancy is of paramount importance.

@mcquin: which lexicographic order? On OS X, the files `A1.tif, A2.tif, A3.tif, & A12.tif` sort `1,2,3,12`, but `1,12,2,3` in CellProfiler. So CellProfiler is ignoring the sorting algorithm used by computers.

**Comment by mcquin** [comment]
The files sort correctly in OS X:

![screen shot 2017-04-20 at 8 25 57 am](https://cloud.githubusercontent.com/assets/4721755/25230769/3d6e62d6-25a3-11e7-93be-5a6bb9e397fb.png)

> Changing the file name modifies the original data. 

I don't understand. Can you provide an example?

**Comment by braymp** [comment]
> I don't understand. Can you provide an example?
One interpretation: You can't necessarily count on the user having w+ access to the image files to be analyzed; the access policies of the institution may not allow this. And if the experiment metadata is being curated, the filename does count as part of the data itself, esp. if no abstraction layer is present.

**Comment by AnneCarpenter** [comment]
I've not fully absorbed this thread, but it appears to me that using LoadData is a decent workaround for the problems described... You can arrange your files in whatever order you like and CP will respect that order (correct?) 

In fact, you can use CP to make a file list, export it, sort it using whatever software/script you like, then import it via LoadData. Could someone more knowledgeable ( @braymp ! ) confirm this is the case?

**Comment by nieder** [comment]
I'll post a screenshot of my files in Finder when I'm back in front of the Mac desktop. But here's a screenshot from Windows Explorer that also sorts files correctly:
![image](https://cloud.githubusercontent.com/assets/1105137/25233443/7199f682-25a4-11e7-87d1-b0b9d02555f2.png)

>>Changing the file name modifies the original data.

>I don't understand. Can you provide an example?

The microscope writes the file A1.tif and stores metadata information about this file in its database. I then rename the file to A01.tif. The database cannot be edited and is now broken.

**Comment by nieder** [comment]
@AnneCarpenter LoadData says it is a legacy module. Will this be kept in CellProfiler moving forward or will it be deprecated and removed eventually?

**Comment by braymp** [comment]
> In fact, you can use CP to make a file list, export it, sort it using whatever software/script you like, then import it via LoadData. Could someone more knowledgeable ( @braymp ! ) confirm this is the case?

Yes, that's true: whatever order the image sets are listed in LoadData, that's the order they are processed in.

**Comment by 0x00b1** [comment]
> The microscope writes the file A1.tif and stores metadata information about this file in its database. I then rename the file to A01.tif. The database cannot be edited and is now broken.

Have you tried configuring your microscope to pad the filename?

Unfortunately, I don’t foresee on working (or thinking about) this anytime soon. I’d encourage sending a pull request.

**Comment by 0x00b1** [comment]
Because this is the type of issue that becomes needlessly contentious, I’m going to close the issue until there’s an update (e.g. a pull request). I think the [forum](http://forum.cellprofiler.org) is the best place to discuss workarounds.

**Comment by AnneCarpenter** [comment]
Agree - Mark confirms that using LoadData is a good workaround to this problem.  Sorry, @nieder we are pretty strapped for time so this just can't be a priority, but to answer your question, despite the discouraging messaging about LoadData we rely on it quite a bit so don't foresee it departing us anytime soon :)

**Comment by bethac07** [comment]
Comment on this, since it just popped up in the [forum again](http://forum.cellprofiler.org/t/order-of-groups-is-lexicographically-even-for-meta-data-but-meta-data-is-not-zero-prefixed/3660/4); I played with @karhohs  dataset he added up here and found a way to do it in CP 2.2 or 3.0 as currently written.  

If you extract whatever information (well column, timepoint, etc) as a piece of Metadata in the Metadata module, set the Metadata data type for that value to “Integer”, and then in the NamesAndTypes module use “Metadata” as the “Image set matching method” (and pick your integer-containing metadata), this should work in both CP 2.2 (first image) and 3.0 (second image). All 3 steps (extract metadata, set as integer, use as image set matching method) must be present to work in my hands.

LoadData of course also works too 😄 

![image](https://user-images.githubusercontent.com/6721515/33090484-232cea0a-cec2-11e7-84c8-99cdd86a77fc.png)
![image](https://user-images.githubusercontent.com/6721515/33090492-2bb422a6-cec2-11e7-8e57-0f803e45f88e.png)
