### ISSUE TITLE
EnhanceOrSuppressFeatures (Circles) returns blank image in 2D

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#2769]
the output:
![image](https://cloud.githubusercontent.com/assets/156232/26228457/fdfe66b6-3c07-11e7-9ef8-e35949ddc928.png)

**Comment by AnneCarpenter** [comment]
Can you please attach example pipeline, images?

**Comment by karhohs** [comment]
No problem!

![testimage](https://cloud.githubusercontent.com/assets/156232/26265941/3a777886-3cb1-11e7-8265-4482a86c5227.png)

[circles_test.cppipe.txt](https://github.com/CellProfiler/CellProfiler/files/1015499/circles_test.cppipe.txt)

**Comment by mcquin** [comment]
@karhohs Try using EnhanceEdges first, and use that image as the input.

**Comment by karhohs** [comment]
@mcquin EnhanceEdges doesn't appear to affect the output of EnhanceOrSuppressFeatures-Circles.

#### Enhance Edges
![image](https://user-images.githubusercontent.com/156232/29838891-81421b68-8cca-11e7-8851-9d00df2e5191.png)

#### EnhanceOrSuppressFeatures-Circles
![image](https://user-images.githubusercontent.com/156232/29838923-9dea84c6-8cca-11e7-9d00-5b70a45c5a8d.png)

FWIW option aside from Circles in EnhanceOrSuppressFeatures outputs the expected results, e.g. speckles

![image](https://user-images.githubusercontent.com/156232/29839056-f89c465c-8cca-11e7-9894-97cf87d53c7f.png)

**Comment by DavidStirling** [comment]
A few years late, but I've been looking into this. The module is actually applying the transform correctly. The problem is that, in an image consisting almost entirely of noise, the transform finds partial circles everywhere and so the entire image becomes washed out. EnhanceEdges is typically needed to get useful results from this transform, as mentioned in the help.

With regards to the image in the initial post, the problem there is that the transform is expecting bright circles rather than dark ones - it's detecting circles in the background. Inverting that image first may provide better results.
