### ISSUE TITLE
Cell Profiler: IdentifyPrimaryObjects Problem

### ISSUE THREAD

**Issue by dpsrdhr** [CellProfiler/CellProfiler#2825]
Hello, 
I have the following pipeline: 
![screen shot 2017-07-24 at 12 22 43 pm](https://user-images.githubusercontent.com/30421367/28548400-aeebeb74-7088-11e7-835b-14ee191a2bad.png)

**I used the LoadImages Module instead of the typical Load Modules because I needed to group images of the same field of view and analyze each channel separately to identify a certain cell type present in the images.

I was having a problem with the IdentifyPrimaryObjects module because it is very inconsistent with the accepting of objects. Clarification: It segments the objects well, given the parameters, but does not accept these segmented figures as objects, even if the most lenient parameters are used. 
![pipeline](https://user-images.githubusercontent.com/30421367/28549646-5608281c-7090-11e7-8ec4-e3210807ff0e.png)

There are trials when it correctly identifies and objects of the same image and other trials where it does not accept objects of the same image. Please let me know what I can do. Thank you!

**Comment by AnneCarpenter** [comment]
Hi there! Looks like your issue was overlooked for a while... sorry about that. 

Could you please post a pipeline and the images needed to feed the pipeline so we can try to diagnose it? 

You might also try downloading the very latest version of CP to see if the issue goes away:
Mac: https://s3.amazonaws.com/cellprofiler-releases/CellProfiler-nightly.dmg
Windows is https://s3.amazonaws.com/cellprofiler-releases/CellProfiler-nightly.exe

**Comment by mcquin** [comment]
Closing: no update
