### ISSUE TITLE
Assess and remove "File > Run Multiple Pipelines"

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3006]
Just not sure if there is any major rationale to keep this? It appears to have been broken at 2.1, per this text found in content.py which has "RUN_MULTIPLE_PIPELINES_HELP"; not sure what the status is in CP 3.0:

> -  CellProfiler 2.1 project files are not currently supported.
> -  Pipelines from CellProfiler 2.0 and lower are supported.
> -  If you want to use a pipeline made using CellProfiler 2.1, then you
>    need to include the project file list with the pipeline, by selecting
>    *Export > Pipeline…*, and under the “Save as type” dropdown, select
>    “CellProfiler pipeline and file list”.

Incidentally, I don't see any help for running multiple pipelines listed in CP's main menu... I suspect you are supposed to get to this help by doing File > Run Multiple Pipelines and then choosing the ? button (but currently nothing happens when you do so).

**Comment by mcquin** [comment]
Odd! 

File > Run Multiple Pipelines works in the GUI for me (OS X, source).

Is this feature used? /cc @bethac07 @karhohs

**Comment by AnneCarpenter** [comment]
Note that I didn't test whether the functionality actually works (bc I was using the nightly where nothing worked). That is cool that it does! 

That leaves me with a strong prior to leave it in, then. 

We could wait for Sentry data (hope we have that for menu items like this?) but we could also do a poll about any features we are thinking about ditching, on the Forum? Not a great mechanism to capture the whole audience but at least some power users are there who might be aware of some of the lesser used use cases.

**Comment by bethac07** [comment]
I actually used to use it quite a bit in the "old days", but haven't recently.  The couple of known use cases I can think of:

* Running a pipeline and having it "trigger" the next one- ie set the illumination correction pipeline to run, then the analysis pipeline once the illumination correction images are available.  
* Running multiple experiments that can't be batched due to memory etc issues- like running TrackObjects in LAP with the second phase on, you don't actually want too many movies per "run" because the memory/temp space/data export gets really wonky the more data you're trying to handle.  

These are reasonable and nice to have, but I don't think I'd cry if it went away.  Anne I'm not sure Sentry would capture this but someone else will know better than I do.

We haven't had great luck attracting responses to forum threads for things like "What do you think of removing this feature"; a survey might be a better mechanism for that.

**Comment by mcquin** [comment]
Good to know, Beth!

Let's keep it for now, and verify its functionality.

**Comment by DuaaAli** [comment]
I followed the instructions in the help menu to Run Multiple Pipelines and it seems to be working!

**Comment by bethac07** [comment]
This doesn't work with pipelines that use the 4 input modules- it should be updated to use those, or be removed in the 4.0 release.
