### ISSUE TITLE
Remove unnecessary setting in IdentifyPrimary declumping?

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3112]
(not urgent, and perhaps it's too challenging to fix the logic in which case it is fine as is)

I came across this in the documentation of IdentifyPrimary:

*{UN_NONE}:* If objects are well separated and bright relative to the            |
   | background, it may be unnecessary to attempt to separate clumped objects.   | 
   | Using the very fast *{UN_NONE}* option, a simple threshold will be used to       |
   | identify objects. This will override any declumping method chosen in the    |
   | settings below.   

What seems odd is that it says "This will override any declumping method chosen in the settings below." and the corresponding setting says a similar thing. Usually, don't we have the settings appear and disappear when they are not relevant?

**Comment by mcquin** [comment]
The documentation can be updated. Choosing "None" removes the declumping setting options that usually follow:

With declumping:
![screen shot 2017-09-13 at 11 14 06 am](https://user-images.githubusercontent.com/4721755/30385285-b060669c-9874-11e7-8e67-6f0b58dbb450.png)


Without declumping:
![screen shot 2017-09-13 at 11 12 58 am](https://user-images.githubusercontent.com/4721755/30385225-86815d2c-9874-11e7-8b44-bf6d1e9ff89e.png)

**Comment by AnneCarpenter** [comment]
I'm happy to update documentation, but I am a little nervous to muck about here. 

You are right if you set the first declumping Q (Method to distinguish clumped objects) to none, all subsequent declumping things disappear as shown. 

But if that one is set to, say, Intensity, then the NEXT one (Method to draw dividing lines between clumped objects) pops up. It has a None option and selecting None there still leaves other declumping options. I think the documentation is accurate for what is actually happening. 

I think what the module needs is fixing some of that logic of settings displays internally, however, it does not seem prudent to do this immediately before a major release!

<img width="651" alt="untitled2" src="https://user-images.githubusercontent.com/1213811/30386391-ad5c10d8-9877-11e7-898a-193ab9227b64.png">

**Comment by mcquin** [comment]
Ah, okay. I think I see what's going on...

1. The [documentation for 'Method to distinguish clumped objects'](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/identifyprimaryobjects.py#L495-L499) can be updated with the line "This will override any declumping method chosen in the settings below." removed, since no declumping options appear when "None" is selected there.

1. The [documentation for 'Method to draw dividing lines between clumped objects'](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/modules/identifyprimaryobjects.py#L552-L556) is correct until we decide if/to hide the setting 'Method to distinguish clumped objects' (and other declumping options).
