### ISSUE TITLE
Reconcile documentation about thresholding - threshold.py vs. measureimagequality

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3145]
I believe these are the only two modules that contain text explaining three-class thresholding. I imagine the others (identifyprimary, etc) grab their text from threshold.py?

So, I think that measureimagequality needs to also grab its help text from threshold.py 

At the same  time, the text in threshold.py might be written a bit nucleus-centric. That is maybe ok but if you're doing this a read-through would be in order to see whether the help as written looks just as correct sitting in the other modules as it does in IdentifyPrimary.

**Comment by minh-doan** [comment]
I don't quite understand the second part
"if you're doing this a read-through would be in order to see whether the help as written looks just as correct sitting in the other modules as it does in IdentifyPrimary."

**Comment by AnneCarpenter** [comment]
There is a description of three-class thresholding in threshold.py and I believe a few modules grab that text as a variable. This is nice so we only need to update the text in one place. Therefore we want measureimagequality to also grab its help text from threshold.py

However, we also need to be sure the text actually makes sense in each context where it's used. So you should read the text in threshold.py and ensure it makes just as much sense in the context of  measureimagequality (where you will be placing it) as in identifyprimaryobjects (where it already is located).

Does that help?

**Comment by minh-doan** [comment]
I see, very clear now.
I'll see if I can do this, or maybe part of it 😁

**Comment by bethac07** [comment]
From the poking around I just did, it seems like this is actually not straightforward at all; when IPO (and ISO, etc) call the documentation from Threshold, it's because they're literally calling all of Threshold's _actual settings_.  Because of how MIQ can calculate many thresholds and has to go through all of them iteratively (then checks a bunch of stuff for duplication, etc), there's a ton of stuff that breaks everytime both Minh and I tried to tweak it.  We can live with the duplicated documentation here, when the module gets what's an inevitably needed under-the-hood restructure the settings will likely be ported from Threshold anyway.
