### ISSUE TITLE
Move modules from Advanced to plugins unless unique or needed for 3D

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3219]
Some of us want to add modules that represent core image processing functions, akin to those found in scikit-image. A subset of such modules currently reside in Advanced. Modules like this can be small and cleanly written and are readily understandable/findable by image processing experts.

Some of us want to minimize the number of different options presented to the user, even in a category like Advanced. The idea here is to instead group multiple functions together into a single module whose name is meaningful to our biologist audience (e.g., "Morph" contains dilation, erosion, closing instead of having each of those be a separate module; "Smooth" contains gaussian filter and other options for smoothing). The code inside each large module like this is more complex, but it does allow all related options to be maintained together rather than as separate but almost identical modules.

We currently have both types of modules and thus redundant functionality. We should consider whether we really want to commit to maintaining both styles of modules as of 3.0.

Some options to handle the situation:
1) Move modules currently in Advanced to Plugins, so we can postpone a decision about how to handle these without breaking compatibility in the future. Exceptions could be (a) modules offering 3D functionality not present in non-Advanced modules, and (b) modules that are not redundant w existing modules. It may be that few modules actually pass these filters though!
2) Make a new category just for the core image processing functions. Not sure what the name could be. This does commit us to maintaining two sets of modules for the same functionality, though, which comes at a cost.
3) Selectively eliminate a few modules that are more obviously redundant, such as ClearBorders which is now redundant with FilterObjects ( #3218 ). If we do this we could debate each in our Google sheet list of modules so we can weigh in on each category.

The list of modules currently in Advanced is below. Note that "redundant" means "I think, in theory, redundant but it may be that the regular CP module is not 3D yet so actually the module is still needed":

(redundant w FilterObjects):
RemoveObjectsBySize
ClearBorder

(redundant w ExpandOrShrink):
ShrinkToObjectCenters

(redundant w Smooth):
GaussianFilter 
MedianFilter

(redundant w Morph):
Opening
Closing
Dilation
Erosion

(not redundant w anything, to my knowledge):
MatchTemplate
MorphologicalSkeleton
ReduceNoise

(redundant w parts of IdentifyPrimary, I think):
RemoveHoles
Watershed
Label
MedialAxis (I guess this is a distance transform?)

**Comment by AnneCarpenter** [comment]
And I should say: I'm honestly not sure what my preference is here!

**Comment by mcquin** [comment]
A few thoughts on combining modules:

- Skeletonization was a feature of **Morph**. We could move **MorphologicalSkeleton** back to **Morph**. However, **Morph** is not fully 3D compatible.
- **ShrinkToObjectCenters** is nominally different from **ExpandOrShrink**, which tries to preserve holes in objects whereas **ShrinkToObjectCenters** places a pixel at the centroid. Furthermore, **ExpandOrShrink** doesn't fully support 3D. I've looked at the code and some of the operations are easily extended to 3D, while others will take a lot more work.
- **IDPrimary** is kind of a nightmare. I've spent weeks on it, on at least two separate occasions, and it's still not 3D compatible. Complaints aside, some of the hole filling functions we use from other libraries don't have the same behavior in 2D and 3D. This makes the update extra challenging. 
- **MedialAxis** can be moved to CellProfiler-plugins
- **ReduceNoise** can be standalone in *Image Processing*, or combined with **Smooth**.

Some of the Advanced modules are "standalone" because their counterparts contain functionality which is difficult to update to 3D. We tried to make it such that a module either completely supported 3D or it didn't. 

If we are going to merge *Advanced* modules into their *Image Processing* equivalent, it is my opinion that we would need to upgrade the entire module to 3D. There is not an easy way to indicate an operation in a module doesn't support 3D. The best we could do is indicate an error (red "x") in the GUI when an unsupported operation is selected, and document "supported/unsupported" in the settings documentation.

A few thoughts on the other presented options:

I'm -1 on moving modules to CellProfiler-plugins. This would mean moving nearly all of CellProfiler's 3D support into another repository. Adding an installation step could discourage users who want that "it works out of the box" experience.

I'm -1 on two categories. It's sort of the solution we have now; we call that category "Advanced". ;)

**Comment by AnneCarpenter** [comment]
Super helpful. Good to know that (1) isn't really an option because few of the modules pass the filters. And it's true (2) doesn't really help too much!

It sounds like you don't find it too terrible to do this variant of (3), is that right? 
4) Remove any modules that actually ARE 100% redundant right now (which are few), but retain the remaining (in-theory-redundant but in-actuality-not-yet-redundant) modules in CP 3.0 and remove them later when/if the functionality is actually integrated.

I'm supportive of this option! I'd thought it might make life miserable later. I could imagine adopting a convention where "Advanced" modules aren't guaranteed backwards compatible which could make this more palatable.

**Comment by mcquin** [comment]
> I could imagine adopting a convention where "Advanced" modules aren't guaranteed backwards compatible which could make this more palatable.

👍 I think this is the best way forward.

There's a chance there may be an upgrade path between a few modules (e.g., **MedianFilter** to **Smooth**), too. But I can't guarantee it just yet.

**Comment by 0x00b1** [comment]
Most of my feelings about this issue are around simplifying CellProfiler’s architecture. I don’t have much of an opinion about usefulness (I’m always surprised to learn what are useful and useless modules), but I do have opinions about maintaining CellProfiler and encouraging contributions to CellProfiler (either in the form of architectural changes or new modules). For example, I would strongly encourage us to depreciate modules that circumvent CellProfiler’s concurrency architecture (e.g. Morph) in favor of smaller thread-safe modules (e.g. Closing, Dilation, Erosion, Opening, etc.).

Here’s a list of problematic modules that we should consider refactoring or replacing with thread-safe alternatives:

- CalculateStatistics
- ClassifyObjects
- FilterObjects
- FlagImage
- ImageMath
- MeasureGranularity
- MeasureImageAreaOccupied
- MeasureImageIntensity
- MeasureImageQuality
- MeasureObjectIntensity
- MeasureObjectIntensityDistribution
- MeasureObjectSizeShape
- MeasureTexture
- Morph
- OverlayOutlines
- StraightenWorms
- Tile
- UnmixColors

**Comment by 0x00b1** [comment]
(Images, Metadata, NamesAndTypes, and Groups are also problematic but they have their own unique issues that are worth discussing elsewhere.)

**Comment by AnneCarpenter** [comment]
I think this issue can be closed because we discussed it at coding day, made decisions about whom to move where, and made issues for those (which I believe are complete now). 

@0x00b1 and @mcquin you might want to have a look over this issue to see if anything else discussed ought to be made into a new issue.
