### ISSUE TITLE
Documentation - elaborate on Smooth/CorrectIlluminationCalculate options

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#3224]
Re. options: Splines and Convex Hull... are they recommended, are they slow? Right now they are just described by pros/cons are not explained. I'm hoping someone has hands-on experience to add, but no big deal if not: @karhohs @bethac07

**Comment by braymp** [comment]
Convex Hull was designed with the BF worms in a well in mind. However, I've occasionally found it useful for other IAD projects with similar intensity profiles.

I forget what project Splines was implemented for. Depending on the settings, it can be slow; the more control points included, the slower it is to compute. However, for *really* irregular illumination/background profiles, it can help since it has the most flexibility. The original paper has more use case: http://www.cb.uu.se/~joakim/publications/SCIA_2001_J_Lindblad.pdf

**Comment by AnneCarpenter** [comment]
Super, I will add this to the help. Thanks a lot!
