### ISSUE TITLE
RemoveHoles should fill holes in labeled images

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler#3369]
Here is an image documenting the issue.  Also posted this issue to the forum.

![image](https://user-images.githubusercontent.com/20077409/32252592-4aec1e64-be53-11e7-8b67-e5d6930a272d.png)

**Comment by mcquin** [comment]
Verified the behavior with the following pipeline:

1. Threshold
2. Label
3. ConvertObjectsToImage (16bit)
4. RemoveHoles

The output is a blank image. When provided a binary image (e.g., the output of Threshold), the filled binary image is returned.

**Comment by AetherUnbound** [comment]
@mcquin What does the output of that filled binary image look like? Since a number of our images don't have distinct borders (like the one @derekthirstrup posted), that image would come back nearly all white. 
![image](https://user-images.githubusercontent.com/10214785/32566987-abbe9868-c46e-11e7-8522-16dd5dc69f1d.png)


I have an idea for how holes could be removed in a labeled image, and could add it as an additional module if that seems sensible.

**Comment by mcquin** [comment]
@AetherUnbound Yes, in this case the returned image would basically be all white which, though technically correct behavior, is not the result you and @derekthirstrup are looking for.

I'd absolutely encourage you to submit a module which fills holes in labeled objects. :)

**Comment by AetherUnbound** [comment]
@mcquin You're right - the technically correct behavior is not the desired behavior! 

Awesome, I'll go ahead and start work on that module. I know your PR is related to this issue, but I'd like to keep the issue open until I've submitted a PR with the labeled-filler module if that's alright.

**Comment by mcquin** [comment]
Sounds good. I'll assign you to the issue.

**Comment by AetherUnbound** [comment]
For context, I'm a software developer that works closely with @derekthirstrup at the Allen Institute for Cell Science. We've got a few modules we'd like to add and we may come across other changes/modifications. If I'm not overstepping myself, I'd love to be added as a collaborator! Otherwise, I'll continue to work through the external revision process.

**Comment by mcquin** [comment]
Nice to meet you! Since we don't have a defined policy on adding collaborators to the project, I think it'd be best if you continued to contribute externally. I know it's super annoying. It's definitely something we should figure out.

**Comment by AetherUnbound** [comment]
Gotcha. I think per AICS's standards we would want to add modules through the external contribution channel anyway. I only ask as a convenience for things like labeling @derekthirstrup's issues, adding reviewers, etc :)

**Comment by AetherUnbound** [comment]
With the two modules made in #3382 and https://github.com/CellProfiler/CellProfiler-plugins/pull/30, this issue has been resolved!
