### ISSUE TITLE
Improve visualization for low-contrast images

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3396]
A couple different CP power users/friends of the lab have now reported so on [the forum](http://forum.cellprofiler.org/t/cp3-log-normalized-gives-black-image/5288/3).

![image](https://user-images.githubusercontent.com/6721515/33433601-2dbb266e-d5aa-11e7-949a-1b7dd625a01b.png)

**Comment by mcquin** [comment]
Yes, the log-normalization code was changed in https://github.com/CellProfiler/CellProfiler/pull/2929/commits/b8c9621adb50e41319d55f2ca79e4e0e7c580cb8.

Previously, log adjustment was made across all channels. In CP3 in happens channel-wise. I wonder if this accounts for the difference.

**Comment by bethac07** [comment]
I actually wonder if it's that we're no longer clipping to min and max before log normalizing- particularly in pretty dim images I imagine that would make a big difference.

**Comment by mcquin** [comment]
Possibly! The [scikit-image documentation](http://scikit-image.org/docs/dev/api/skimage.exposure.html#skimage.exposure.adjust_log) states that it rescales the image to [0, 1] before performing log-normalization. The previous clipping rescales to the min of strictly positive values.

**Comment by mcquin** [comment]
Picture time!

The previous normalization clipped the values so that it never had to take `log(x)` for `x <= 0`. The correct formula for log normalization takes `log(x + 1)`, and assumes all `x >= 0`.

Using the example fly images, here's the difference between log normalization in CP 2.X and CP 3.X. The CP 2.X version is definitely much brighter than in CP 3.X, though a bit unnatural/over-exaggerated:
![normalization](https://user-images.githubusercontent.com/4721755/34618355-8170e6da-f20c-11e7-9128-86d761ab32ee.png)

I tried rescaling the pixel values in the image from [minimum, maximum] to the [0, 1] range after applying log normalization and got a nice result:
![normalization_clipped](https://user-images.githubusercontent.com/4721755/34619343-d010c08c-f20f-11e7-87e1-1db13ad29653.png)

I like the log-normalized and stretched image best, and I think it could work well for low-contrast images. It's also closer to the behavior of CP 2.X, and uses the correct function for log transformation.

What are your thoughts, @bethac07 ?

**Comment by bethac07** [comment]
Can you try your new version it on the image I'm attaching here?  Sometimes it's really nice to be able to blow out the contrast, to pick up things like the dim speckles you can see in the log transform in 2.2 but not in 3.0.

![image](https://user-images.githubusercontent.com/6721515/34621531-945bb8aa-f217-11e7-9b60-52309f4a4f71.png)


[r06c05f09p01-ch2sk1fk1fl1.zip](https://github.com/CellProfiler/CellProfiler/files/1607438/r06c05f09p01-ch2sk1fk1fl1.zip)

**Comment by mcquin** [comment]
It enhances the speckles some, but not nearly as much as 2.2 does:

![log_normalized](https://user-images.githubusercontent.com/4721755/34622447-48845e10-f21b-11e7-857a-967cca29e650.png)

**Comment by bethac07** [comment]
Would it be possible to add a 4th option then instead?  skimage's rescaling does allow you to pass in a gain, so in addition to having "Raw" "Normalized" "Log normalized" could we add "Log normalized (5X* gain)"?  I totally see the value from a code perspective of doing it mathematically correctly and using a standard function with no maintenance burden, but from an assay dev perspective being able to see dim things in images is sometimes really important.

(Note that 5 as the gain factor is totally made up, we could play with a couple different factors to see what's logical)

**Comment by mcquin** [comment]
Yeah! Totally! What do you think about this:

![screen shot 2018-01-05 at 2 52 50 pm](https://user-images.githubusercontent.com/4721755/34625818-2c1a149c-f228-11e7-90c3-69f0a1396a50.png)

Gamma adjustments are great for manipulating contrast. I'll add a blurb on how to tune gamma, if this is something you think you'd and others would like to see in CP.

**Comment by bethac07** [comment]
That'd be great, but ideally it'd be nice to have something we can set as a default in Preferences- often you want to do this for every image you look at in the entire assay dev process.

**Comment by mcquin** [comment]
Good point. I'll see what I can whip up.
