### ISSUE TITLE
RescaleIntensity fails when using "Min of all images" and "Max of all images"

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3398]
From [the forum](http://forum.cellprofiler.org/t/issue-with-integrated-fluorescence-intensity-values/5408/3)

When using the pipeline and images below (which has RescaleIntensity set to set the "Minimum of all images" and "Maximum of all images" to 0-65536, user gets the following error.  User sees it in 2.2 and 3.0.  I validated on my machine (3.0 only); error is resolved by instead setting 0-1 to 0-65536.

Seems to be identical to bullet point 2 in #3196 

```
Worker 0: Failed to prepare group in module RescaleIntensity
Worker 0: Traceback (most recent call last):
Worker 0:   File "CellProfiler\cellprofiler\pipeline.py", line 2306, in prepare_group
Worker 0:   File "CellProfiler\cellprofiler\modules\rescaleintensity.py", line 338, in prepare_group
Worker 0:   File "CellProfiler\cellprofiler\pipeline.py", line 2002, in run_group_with_yield
Worker 0:   File "CellProfiler\cellprofiler\pipeline.py", line 2022, in run_module
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1758, in run
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1810, in add_image_provider
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1848, in add_simple_image
Worker 0:   File "CellProfiler\cellprofiler\modules\namesandtypes.py", line 1875, in add_provider_measurements
Worker 0: AttributeError: 'MonochromeImageProvider' object has no attribute 'scale'
```

[Images and Pipline.zip](https://github.com/CellProfiler/CellProfiler/files/1519237/Images.and.Pipline.zip)

**Comment by AetherUnbound** [comment]
This problem is a bit more pervasive than I first suspected it would be...

It looks like `namesandtypes.py` Line1867 (the call to `get_image`) is actually modifying the `provider` objects by adding the `scale` attribute. This occurs at  `loadimages.py` L3328. This is a bit counter-intuitive, since the provider is not specified whatsoever in the `get_image` call. It seems like we might need a default value for `provider.scale`, although I'm not sure what downstream effects that might have. @mcquin @0x00b1 ?
