### ISSUE TITLE
Evaluate if MeasureObjectSizeShape should use regionprops for 2D measurements

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3501]
There is a lot of overlap between the 2D measurements MeasureObjectSizeShape calculates (mostly from centrosome) and those calculated by `skimage.measure.regionprops` - it is likely close to 100% but I have not checked exhaustively.  As we use regionprops for the 3D measurements, we should evaluate whether the values and the processing speed would be comparable if we used it for the 2D measurements as well.

**Comment by shntnu** [comment]
When profiling skopy, Allen and I found that `convex_area` and `solidity` were super slow – would be great if you could independently verify that.

**Comment by DavidStirling** [comment]
Per #4102, centrosome convex hulls are still needed to capture feret diameter measures as regionprops lacks these ([for now!](https://github.com/scikit-image/scikit-image/pull/4379)). Solidity wasn't too bad with Skimage, but can be slow with 3D so I've made that an optional feature in 3D mode. Do we want to record Skimage `convex_area`? I could add that as a new measure if we want it.

Processing speed was generally comparable in my testing, although it'd be slightly slower with the new 'advanced features' due to the numerous new measures that are available.
