### ISSUE TITLE
For some 3D measurements should we give the option to add slicewise measurements too?

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3505]
Many of the types of objects biologists want to measure in 3D are asymmetrical or polarized- in tissues and organoids for example there's often a "top" and "bottom" cell surface that are quite distinct.  It's worth considering whether or not we should therefore give the option in 3D measurement modules to also report slicewise 2D measurements.  I have no idea how complicated it is from a code perspective, so feel free to reject on that basis, but I wanted to bring it up.

**Comment by mcquin** [comment]
I am opposed to implementing this for all 3D features simply due to the additionally overhead of the computations that will then cause the 3D measurement modules to slow down significantly. In the cases where directionality matters (like polarization, as you mentioned) then, I think, a specific measurement should be implemented to capture that feature.
