### ISSUE TITLE
CP startup slow on Windows

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3537]
From the [forum](http://forum.cellprofiler.org/t/analysis-starts-slowly-with-cp3-0-0/5915), but I can personally confirm the slow GUI startup (~15-20 seconds when starting from source, ~40 when starting from compiled on my machine)-

>Hi,
I was trying CP 3.0.0 noticed it takes quite a long time before the actual analysis gets started. It doesn’t feel particularly slow in test mode, or once the processing gets going. So I’m wondering about the delay:
```
Starting workers on address tcp://127.0.0.1:62162
Progress Counter({u'Unprocessed': 36})

# after 6-7 minutes...

Worker 1: Starting job
Progress Counter({u'Unprocessed': 35, u'InProcess': 1})
Worker 1: Doing job: 1
Worker 1: Wed Mar 28 17:25:54 2018: Image # 1, module Images # 1: CPU_time = 0.0
0 secs, Wall_time = 0.00 secs
Worker 1: Wed Mar 28 17:25:54 2018: Image # 1, module Metadata # 2: CPU_time = 0
.00 secs, Wall_time = 0.00 secs
```
>Pipeline doesn’t seem to matter, it’s the same with a pipeline with only IdentifyPrimaryObjects. I’m using the new default input modules.
This seems to be about CP process start up in general. It takes about 35s for the GUI to show up. When I tested with maximum number of processors set to two, progress started at about 1min 15s; with 4 processors, at about 2min 30s. And the ~7min corresponds with having all 12 threads in play.
Does that make sense? Should it be faster? The PC has Intel® Xeon® CPU X5670 @ 2.93GHz and 24 GB of RAM. CP 2.2.0 doesn’t have this delay.

**Comment by m-westberg** [comment]
To confirm, we are experiencing the same issue under comparable conditions.

**Comment by zdedenn** [comment]
I'm experiencing the same with CellProfiler 3.1.8 on Windows 7. 
In my case with 4 workers it seems that another (at least) four full instances of CP are started, which takes quite long (mainly due to the antivirus having to scan the whole CP executable). The worker that starts first does all the work and eventually all the workers are terminated. The other workers did nothing, just kept the CPU and disks busy! That's why for simple pipelines the whole process is faster when the number of threads is limited to one.
Now the zero dollar question: Can this be fixed? I'm not sure what the older versions of CP did differently...

**Comment by edlaw89** [comment]
I am also experiencing the same issue when compiling from source for CP3.1.8 on Windows 10, except in my case it didn't start even after 20 minutes, however I noticed it started processing a little once I cancelled the analysis run.

Solved this by running cellprofiler headless

**Comment by DavidStirling** [comment]
I believe this should be largely resolved in CellProfiler 4 thanks to the IO fixes and other efficiency improvements. Packaged versions also shouldn't suffer a startup speed penalty in this release. Perhaps re-open this if we still find problems down the line?
