### ISSUE TITLE
Is SavedCroppedObjects meant to be 3D?

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler#3546]
@bethac07 pointed out in the documentation for the SavedCroppedObject that it states this module is not 3D. However, the module has,
```
def volumetric(self):
   return True
```

If 3D is to be incorporated into this module, then PNG files cannot be used to reduce storage requirements since this image format does not support volumetric images.

**Comment by bethac07** [comment]
I went back to the blame and the module spreadsheet we had:

`volumetric` being True is part of the initial commit, so it seems like the initial intention WAS for it to be 3D

In the module spreadsheet, the "3D" column is marked, rather than with Y or N, with `probly not` .  We'd need to run a script probably to figure out who wrote that or when, but it's a snarky comment so I'll just go ahead and claim that was my fault.  

The 3D tests were passing, so I'm thinking it does actually support 3D though.  My guess is that we want to preserve that if we can (perhaps by switching to compressed 8 bit TIFs rather than by switching to PNGs), but does anyone else feel differently?

**Comment by karhohs** [comment]
I added an option to save as compressed TIFF or PNG re #3544

**Comment by bethac07** [comment]
Resolved by #3545
