### ISSUE TITLE
Multiple failing tests after Scipy 1.1 release

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3565]
https://travis-ci.org/CellProfiler/CellProfiler/builds/376596529 (this is of a PR, but there were only doc changes in it not code changes)- The vast majority seem to be variations on the following issue:

` TypeError: 'numpy.float64' object cannot be interpreted as an index`

**Comment by AetherUnbound** [comment]
Haha I was just looking into this! It seems to be caused by this: https://scipy.github.io/devdocs/release.1.1.0.html#deprecated-features (second to last line)

**Comment by AetherUnbound** [comment]
For now, I'm going to pin the version in the Travis fix branch, and address the root cause later down the line.

**Comment by bgriffen** [comment]
Hi @AetherUnbound; could this also be affecting [this issue](https://github.com/CellProfiler/CellProfiler/issues/3582), found by a few users? It is fairly important because basically, the output of a very vanilla CP run now does not map objects 1:1 (e.g. row index in Nuclei.csv and Cells.csv are not the same). I wasn't sure if it effects MeasureObjectIntensity.

**Comment by AetherUnbound** [comment]
@bgriffen Hmm, I don't think it's the same problem. The issue described in #3582 is actually one I recently encountered, and it does have to do with the fact that parts of CellProfiler expect that object indices are in order without any gaps (and I agree that's frustrating!). I'll need to discuss this with @derekthirstrup, @bethac07, and @0x00b1 to see what behavior we should be supporting.
