### ISSUE TITLE
Manually split primary objects are not used as seeds for secondary object detection

### ISSUE THREAD

**Issue by youtaro** [CellProfiler/CellProfiler#3621]
With CellProfiler 3.0.0 (and 3.1.5) I am using the Split Mode to split nuclei that were initially identified as one. The resulting EditedObjects screen correctly reflects the nuclei that I have split. However, when I specify the edited objects (split nuclei) as the primary objects to identify secondary objects (cells), cellprofiler still uses the original nuclei prior to splitting as the seed.

If I delete the whole nucleus entirely and manually draw two nuclei, the same problem still occurs.

The workflow was:
IdentifyPrimaryObjects: I used to Identify the nuclei
EditObjectsManually: I used to choose a nuclei and split it
and then
IdentifySecondaryObjects to expand the nuclei.

Can anyone suggest a solution to this potential bug?

**Comment by lauracmurphy** [comment]
Just to add, this originated from the forum 
https://forum.image.sc/t/problem-with-identifying-secondary-objects-from-manually-edited-primary-objects/18842/2

And I've put the pipeline and image set I used to recreate here: https://uoe-my.sharepoint.com/:f:/g/personal/lmurphy5_ed_ac_uk/EsJjpp2y3R5MiGbSxaU2rgEBw2e_wHK1vVR3DH1IL9U2fQ?e=OgDQmV 1

**Comment by AetherUnbound** [comment]
![screenshot_2018-09-15_21-22-03](https://user-images.githubusercontent.com/10214785/45592842-6a20c700-b92d-11e8-8f20-c6c19c224f3d.png)
It also seems like removing a big chunk of objects still affects the identify secondary object stuff. 
In order to troubleshoot this more, do you mind editing the objects in this sample pipeline the way you have been and use the pipeline to save it out? Once you have the image, do you mind posting it here for me to test with?

**Comment by bethac07** [comment]
Possibly related to #3645 ?

**Comment by bethac07** [comment]
Currently can't verify, possibly fixed, reopen if not.
