### ISSUE TITLE
Give modules that operate on an image set a shared color map where appropriate

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#3819]

**Comment by bethac07** [comment]
Definitely-
- [ ] IdentifyTertiaryObjects
- [ ] ExpandOrShrinkObjects
- [ ] ResizeObjects

Maybe-
- [ ] MaskObjects
- [ ] FilterObjects

**Comment by DavidStirling** [comment]
ResizeObjects actually just uses the generic module.py object display function. Fixing it there will therefore also correct FillObjects, DilateObjects and ShrinkToObjectCenters.

RelateObjects already had this applied.

FilterObjects wasn't necessary since the objects are relabelled - colours won't match anyway.

MaskObjects needs fixing before this change can be tested.

**Comment by DavidStirling** [comment]
Having fixed MaskObjects, shared colormaps didn't work on that module since the second image uses subplot_imshow_color rather than subplot_imshow_labels.
