### ISSUE TITLE
JAVA_HOME conflict on Windows

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#3872]
I was unable to launch CellProfiler today, getting then following error: 

![CPBug](https://user-images.githubusercontent.com/26802537/69570871-bf735200-0f8e-11ea-83bc-6ac43a363cf4.png)

After reading around the forum a bit, I found that removing the JAVA_HOME system variable (set to a normal Java installation) got it working again. This is despite CP_JAVA_HOME being set correctly. I'm not sure if this is an issue with JavaBridge, but I'd have thought that the presence of CellProfiler's packaged Java environment should prevent any search for another installation?

**Comment by bethac07** [comment]
Nope; CellProfiler checks JAVA_HOME first, then checks CP_JAVA_HOME if JAVA_HOME isn't set.

**Comment by DavidStirling** [comment]
Thanks. Is there a reason for it to do this? Wouldn't that mean that a normal but incompatible Java install could break CellProfiler?

**Comment by bethac07** [comment]
It's essentially because Javabridge checks JAVA_HOME, and pretty much nothing else; in an earlier build (I want to say 3.1.5), we set JAVA_HOME if it wasn't already set, but that meant that people's OTHER Java using programs sometimes got wrecked in a way that was hard for them to diagnose.  Since CellProfiler can use basically any 64-bit Java (your error message indicates you were trying to use a 32 bit), we'd rather err on the side of letting them use the packaged version if they don't have another JDK, or use their own if they'd like, rather than forcing everything on their computer to use the CellProfiler Java.

We could probably devise a python-javabridge PR to ask it to check CP_JAVA_HOME, but I'm not sure it would be accepted; it's also possible there are cleverer ways to figure how to set this that i haven't figured out.

**Comment by bethac07** [comment]
We wanted to leave it as an option for users to bring their own, particularly for pharma/industry users, but it's a reasonable point we don't do that for Mac (a medium-to-high computer comfort Mac user could change the version, but it's not trivial), so maybe it doesn't actually matter.  Something to think about.
