### ISSUE TITLE
loading stack flex files from Opera

### ISSUE THREAD

**Issue by nataliep4d** [CellProfiler/CellProfiler#3883]
Hi, 
I am struggling with getting CellProfiler understand the images that were acquired using Acapella software. The filenames look as following: 00X00Y00Z.flex, where X=raw #, Y=column #, Z=FOV #. I have no problem extracting this positional information. However, each file is a stack containing 5 images taken from different channels.  
  The legacy module "Load Images" seems to allow me to use the order of the images in a stack to assign each to a separate channel, but using it disables the Images, Metadata, NamesAndTypes, and Groups modules. 
  What is the best way to get that information in the newest Cell Profiler version?
Thank you so much! 
Attached is one of my files (zipped)
[002001004.zip](https://github.com/CellProfiler/CellProfiler/files/4041807/002001004.zip)

**Comment by nataliep4d** [comment]
Also, I tried extracting metadata from image headers, as suggested in the tutorial, but the results don't seem to make sense: 
![image](https://user-images.githubusercontent.com/59295538/72093018-779f5480-32c8-11ea-88a4-cdae29ae25f6.png)

**Comment by bethac07** [comment]
Hi,

The fact that this is a multichannel image should be gettable from your image header (it is in many other file formats), but the particular image you sent appears to be corrupted- I can't open it in either FIJI or CellProfiler.

Try removing your images from the pipeline, reloading them (or at least one or two you know aren't corrupted), hitting the "Update Metadata" button FIRST, then the "Update" button, as demo'ed in the forum post below.

https://forum.image.sc/t/how-to-process-nd2-files/13664/2?u=bcimini

I'd also ask that we move this to the forum if you need additional followup help, since this isn't really a CellProfiler bug per se, and is more likely to be found by someone with the same issue there.
