### ISSUE TITLE
Error while processing Threshold

### ISSUE THREAD

**Issue by NasimJ** [CellProfiler/CellProfiler#3947]
Thresholding after ImageMath (configuration below) resulted this error:
![Screen Shot 2020-03-16 at 9 15 27 PM](https://user-images.githubusercontent.com/55710463/76812509-7ceab500-67cb-11ea-88b0-e86c13ec57da.png)

ImageMath: 
Operation: Subtract
Raise to the power: **0.4**   (**when 1 instead of 0.4, it runs with no error**) 

Threshold:
Strategy: Adaptive 
method: Otsu (3class, background)

**Comment by bethac07** [comment]
Does ImageMath have "set values <0 to 0" and "set values >1 to 1" both set to yes?

**Comment by DavidStirling** [comment]
It appears that wherever subtract generates negative numbers the power function then returns nan. "Set <0 to 0" is applied after the power function so that setting doesn't change the result - we might expect that as nan can't really be assumed as 0 or 1. I'm going to look into what's making it return nan rather than a value and whether this is mathematically correct.

**Comment by DavidStirling** [comment]
On further reading, it appears that this is correct behaviour. You cannot raise a negative number to the power of a fraction (today I learned something). Should we leave this as "not a bug" or would there be value in having a way to handle nan values in ImageMath?

**Comment by bethac07** [comment]
It's definitely a bug in the sense of a user not necessarily knowing their image will produce negative values, and the nan's then persisting downstream and causing errors.

I think my preferred handling would be a "Set nan values to 0?" option (default = yes) below the current set of "Set _ to _" options (with the help explaining this can occur in rare cases such as raising a negative value to a fractional power).
