### ISSUE TITLE
Trouble running plug-ins

### ISSUE THREAD

**Issue by overvalley** [CellProfiler/CellProfiler#4052]
Hello. To run plug-ins on CellProfiler, is it necessary to download the software from source?

**Comment by bethac07** [comment]
It is IF the plugin in question requires extra dependencies CellProfiler does not have (ie, most of our deep learning plugins), it requires you to build from source because the copy of Python inside the CellProfiler downloaded from the website won't have the libraries you need - if the plugin does not add extra dependencies (most, though not all, of our other plugins fit that category), you can use it in CellProfiler installed in python OR downloaded from our website
