### ISSUE TITLE
Possible to install on Linux in 2020?

### ISSUE THREAD

**Issue by tbenst** [CellProfiler/CellProfiler#4136]
**Describe the bug**
Python 2 reached EOL in Jan 2020. I understand python 3 is a "moving target", but[ current instructions](https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation#important-notes) have no chance of working.

**To Reproduce**
Follow instructions on https://github.com/CellProfiler/CellProfiler/wiki/Conda-Installation

**Expected behavior**
Install should succeeed

**Screenshots**
```
Pip subprocess error:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  Running command git clone -q https://github.com/CellProfiler/CellProfiler.git /tmp/pip-req-build-TFuPLw
  Running command git checkout -b v3.1.9 --track origin/v3.1.9
  Switched to a new branch 'v3.1.9'
  Branch 'v3.1.9' set up to track remote branch 'v3.1.9' from 'origin'.
    ERROR: Command errored out with exit status 1:
     command: /home/tyler/lib/anaconda3/envs/cellprofiler/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nMfkYA/centrosome/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nMfkYA/centrosome/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-nMfkYA/centrosome/pip-egg-info
         cwd: /tmp/pip-install-nMfkYA/centrosome/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nMfkYA/centrosome/setup.py", line 84
        **__extkwargs,
                     ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


CondaEnvException: Pip failed
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CellProfiler Version: master
 - Downloaded from the website or installed from source: source
 - If the latter, how: via instructions above

**Additional context**
This package looks awesome and excited to use once installed, thank you!

**Comment by tbenst** [comment]
Might I suggest the below as a placeholder instead?

```
# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: cellprofiler
# in order of priority: highest (top) to lowest (bottom)
channels:
  - anaconda
  - goodman # mysql-python for mac
  - bioconda
  - cyclus # java-jdk for windows
  - conda-forge # libxml2 for windows
  - daf # wxpython for linux
dependencies:
  - appdirs
  - boto3
  - cython
  - h5py
  - ipywidgets
  - java-jdk
  - joblib
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - packaging
  - pillow
  - pip
  - python=3.8
  - pyzmq
  - mahotas
  - matplotlib>2.0.0
  - mysqlclient
  - numpy
  - raven
  - requests
  - scikit-image>=0.13
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
  - wxpython
  - pip:
    - cellh5
    - centrosome
    - inflect
    - prokaryote>=2.4.0
    - javabridge>=1.0.15
    - python-bioformats>=1.4.0
    - git+https://github.com/CellProfiler/CellProfiler.git@v4.0.0rc7
```

**Comment by kushalkolar** [comment]
Hi @tbenst I was having the same exact issue (`NotImplementedError` for line 30 of `cellprofiler/gui/_welcome_frame.py`) on Ubuntu 18.04 LTS. This is not an issue with `mysql`, it's because the `wxPython` on pypi doesn't appear to contain the `wxWebKit`. But the wheels on the wxpython server seem to have it. You also need `webkitgtk` dev packages installed on your system.

This is what I did to get it to work:
1. Install webkit gtk dev packages, not exactly sure which ones are required so I just installed everything:
```
sudo apt install libwebkit*
sudo apt install libwebkit2gtk-4.0-*
```

2. Create a new `python3.8` environment:
```
python3.8 -m venv /share/python-virtual-environments/cellprofiler
source /share/python-virtual-environments/cellprofiler/bin/activate

pip install --upgrade setuptools;pip install wheel
```

3. Install wxPython directly from the wheels supplied on the wxPython server, NOT from pypi. The ones from pypi don't seem to have the webkits.
```pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/ wxPython```

You should be able to replace the `ubuntu-18.04` with `ubuntu-20.04`, see here for all distros that they have wheels for:
https://extras.wxpython.org/wxPython4/extras/linux/gtk3/

**Comment by DerJFK** [comment]
I tried to install CellProfiler on Ubuntu 20.04 according to the instructions [here](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-20.04) and ran into the [issue 4202](https://github.com/CellProfiler/CellProfiler/issues/4202). Then I found your post and installed wxPython not from pypi but get the error message

`ImportError: /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: gst_gl_display_egl_new_with_egl_display`

In installed libwebkit* as you suggested. But still get this error.

**Comment by kushalkolar** [comment]
@DerJFK You might be missing gstreamer plugins, https://bugzilla.redhat.com/show_bug.cgi?id=1499466 , https://gstreamer.freedesktop.org/documentation/gl/gstgldisplay.html?gi-language=c

you should be able tot install gstreamer from the apt repositories: https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c

**Comment by DerJFK** [comment]
@kushalkolar Thanks for your answer. I installed [gstreamer](https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c), but still the same error.

**Comment by kushalkolar** [comment]
@DerJFK not sure, I'd try googling around or see if the cellprofiler devs have any ideas

**Comment by vkhodygo** [comment]
I'd like to raise this issue again rather than try and open a new one.
Current Linux instructions work after some tweaking but the process itself is a nightmare. 

@bethac07  I can try and update the installation guide for Linux but I need some directions: how do you want it to look, how should I test it properly. Also, it would be great to have a Linux package such as `deb` as well, but anything like `Flatpak` or `AppImage` would do as well.
