### ISSUE TITLE
Trouble to launch GUI on ubuntu 18.04 with CellProfiler v4.0.2

### ISSUE THREAD

**Issue by AmandineCornil** [CellProfiler/CellProfiler#4233]
Dear CellProfiler team,

I just installed cellprofiler v 4.0.2 on ubuntu 18.04 and here is the error:
amandine@amandine-linux:~$ cellprofiler
16:50:02: Debug: Adding duplicate image handler for 'Windows bitmap file'
16:50:02: Debug: Adding duplicate animation handler for '1' type
16:50:02: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/home/amandine/.local/lib/python3.8/site-packages/cellprofiler/gui/app.py", line 67, in OnInit
    self.frame = CPFrame(None, -1, "CellProfiler")
  File "/home/amandine/.local/lib/python3.8/site-packages/cellprofiler/gui/cpframe.py", line 348, in __init__
    self.startup_blurb_frame = WelcomeFrame(self)
  File "/home/amandine/.local/lib/python3.8/site-packages/cellprofiler/gui/_welcome_frame.py", line 30, in __init__
    self.content = wx.html2.WebView.New(self)
NotImplementedError
OnInit returned false, exiting...

Do you have an idea of what happened?
Thanks a lot,
Best

**Comment by bethac07** [comment]
Can you confirm your wxPython version? It needs to be 4.1.0

**Comment by AmandineCornil** [comment]
Yes, wxPython is 4.1.0

**Comment by bethac07** [comment]
Can you confirm you have some form of gtk installed? 

Based on [this](https://wxpython.org/Phoenix/docs/html/wx.html2.WebView.html), I wonder if you may also need libwebkit2gtk-4.0-dev ; if you definitely already have GTK installed, do you mind uninstalling wx, installing that library, and then re-installing wx to see if that fixes your issue? If so, we'll be sure to add that to the installation insturctions.

**Comment by AmandineCornil** [comment]
I have libwebkit2gtk-4.0-37:amd64; will try now to switch to libwebkit2gtk-4.0-dev

**Comment by AmandineCornil** [comment]
Ok, succeed to install  libwebkit2gtk-4.0-dev but exactly the same error with CellProfiler

**Comment by DavidStirling** [comment]
Just to check - you re-installed wx after installing webkit?

**Comment by AmandineCornil** [comment]
Yes, of course

**Comment by bethac07** [comment]
And just to extra-confirm, you also have `libgtk-3-dev` as well?

**Comment by AmandineCornil** [comment]
yes, libgtk-3-dev:amd64

**Comment by bethac07** [comment]
How did you install wxPython- building it yourself or from their wheel?  

[This thread](https://discuss.wxpython.org/t/wxdemo-html2-possible-bug/34760/13) makes me think that you might just need to clean your pip cache and force the reinstall of wx- when you reinstalled, it might have fallen back on the old compilation, which if you built it yourself and didn't have the libwebkit2gtk-4.0-dev might have passed the build but still is missing that library.

**Comment by AmandineCornil** [comment]
I cleaned and re-installed everything from scratch (even python and pip) and always the same error. 
For wxPython:  python3.8 -m pip install wxPython-4.1.0-cp38-cp38-linux_x86_64.whl

**Comment by bethac07** [comment]
Based on this and [another issue we noticed](https://discuss.wxpython.org/t/pip-reinstalling-wx-after-wheel-installation-ubuntu-18-04-python-3-8/34878), I think right now ubuntu 18.04 has a bad wx4.1 wheel- I'm working with them to try to get it solved, but not much I can do right now until they fix it.  Very sorry- it seems to be platform specific!

The other option is to ignore that wheel and build wx completely from scratch- we've [updated our Ubuntu 18.04 instructions](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-18.04) to list out all the other packages you'd need to build that wheel- you'd want to uninstall and clear the cache on your current wx, install all those packages, force-re-pip install wx (not from the wheel, just `python3.8 -m pip install --force-reinstall wxPython==4.1.0`), then try to see if CellProfiler is happier.  Unfortunately, the building process can take a few hours, which is why under normal circumstance we'd recommend the wheel.

If I think of anything else, or if I hear that they've fixed their uploaded wheel, I'll be sure to post it here!

**Comment by bethac07** [comment]
Can you try building CellProfiler in a venv? We've added [instructions](https://github.com/CellProfiler/CellProfiler/wiki/Ubuntu-18.04) to do that (make sure you grab libwebkit2gtk-4.0-dev and python3.8-venv first) ; for reasons I don't yet fully understand, it seems to make wx play nicely.

**Comment by AmandineCornil** [comment]
Yes, of course. Now it launched, but with this message. Will try like this
![Capture du 2020-09-14 18-02-04](https://user-images.githubusercontent.com/22766358/93095869-f5133400-f6a3-11ea-8573-9d5db70ffef6.png)

**Comment by AmandineCornil** [comment]
It has been 2 days that I play with cellProfiler. Still have the error message when I launch the software but I think all the options are working well. Just the GUI that freeze some times (could be link to some wxPython issues)

**Comment by bethac07** [comment]
Thanks for letting us know it's behaving overall-well! I'll go ahead and close this, since you now have a working version, but please do let us know if other things crop up.
