### ISSUE TITLE
CellProfiler v4.0.2 doesn't show up on Mac

### ISSUE THREAD

**Issue by minhtran1309** [CellProfiler/CellProfiler#4236]
**Describe the bug**
After downloading the zip file from this website https://cellprofiler.org/releases, I extracted the .app file, copied it to the Application folder, and followed the instruction. 
I could still see the icon open. but no UI showed up. 
I tried to open it through the command line `open CellProfiler.app/` but still no error show. 

I use macOS Mojave v10.14.6. Chip Core i5. Python 3.6.6

**Comment by bethac07** [comment]
How long did you wait? It will take a minute or two on first start up.

Can you also confirm if you saw a message like the one below (exact number may be different?).  For reasons we still haven't been able to track down, on the very first time you open CellProfiler (and only on the first time), this message will pop up, and you won't get the UI until you've said "OK".  Maybe check with Mission Control- the error message is small, it might have hidden behind something else?

![image](https://user-images.githubusercontent.com/6721515/93085634-d8efa280-f663-11ea-8f27-da454c2f1e01.png)

**Comment by minhtran1309** [comment]
after waiting for a while (around 3-4min), I noticed the app turned off without error or message.

**Comment by bethac07** [comment]
Can you try our new 4.0.4 release to see if it works better for you?

**Comment by minhtran1309** [comment]
Hi @bethac07 , I tried to download and open newer version, It still doesn't open but this time it at least shows a message: Application Not Responding as the image below. I check my System Preferences -> Security & Privacy and set the option to Allow apps downloaded to anywhere already. 
Is there any way that I can do to debug the issue? Thanks 
![image](https://user-images.githubusercontent.com/53423600/93540816-25a2e880-f998-11ea-8bef-435d870c7d21.png)

**Comment by dani-carbonell** [comment]
Same problem here with

MacOs High Sierra 10.13.6
Cell Profiler 4.0.5

**Comment by bethac07** [comment]
Sorry, we've realized CellProfiler 4 is only compatible with OSX 14+ due to how our build system is set up; we updated our website yesterday to reflect this.  It may be possible for you to try the new CellProfiler 4 by [installing from source](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29); we don't have access to a 10.13 machine at the moment to check if the instructions we linked will work, but they may be worth a try!

**Comment by bkechava-lilly** [comment]
Getting the same with (app icon on system tray, silent failure) MacOS 10.15.7 and CellProfiler 4.0.5

**Comment by minhtran1309** [comment]
> Sorry, we've realized CellProfiler 4 is only compatible with OSX 14+ due to how our build system is set up; we updated our website yesterday to reflect this. It may be possible for you to try the new CellProfiler 4 by [installing from source](https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29); we don't have access to a 10.13 machine at the moment to check if the instructions we linked will work, but they may be worth a try!

I tried to follow the instruction and built from the source. However, I got into even more problems with centrosome package. 

```
ERROR: Failed building wheel for centrosome
Failed to build centrosome
ERROR: Could not build wheels for centrosome which use PEP 517 and cannot be installed directly

``` 

Try to look around for the solution of centrosome but I only find a few unsolved issues (which have been still opened since 2018).

**Comment by subnet-dev** [comment]
I managed to fix this problem by modifying the file CellProfiler.app/Contents/Info.plist.
You must change the value of "Environment variables" > "JAVA_HOME" by "Contents/" instead of ./Contents.

[Here is my modified Info.plist file (You may need to rename it to Info.plist instead of Info.plist.txt)](https://github.com/CellProfiler/CellProfiler/files/5406787/Info.plist.txt)

CellProfiler must also be able to access the "Documents Folder" folder. System Preferences > Security & Privacy > Privacy > Files and Folders

Hope this fix was able to help you !

**Comment by jshudnall** [comment]
I also have this problem running OS 12.4
