### ISSUE TITLE
IndexError: boolean index did not match index array along dimension 0

### ISSUE THREAD

**Issue by sjmurphy1994** [CellProfiler/CellProfiler#4245]
I had a pipeline that was working until I added a new file set and then received this error - How do I fix the problem?

Worker 0: Tue Sep 15 11:51:22 2020: Image # 1, module Resize # 6: CPU_time = 10.47 secs, Wall_time = 10.37 secs
Worker 0: Error detected during run of module MaskImage#7
Worker 0: Traceback (most recent call last):
Worker 0:   File "CellProfiler\cellprofiler\pipeline.py", line 1924, in run_image_set
Worker 0:   File "CellProfiler\cellprofiler\pipeline.py", line 2034, in run_module
Worker 0:   File "CellProfiler\cellprofiler\modules\maskimage.py", line 168, in run
Worker 0: IndexError: boolean index did not match indexed array along dimension 0; dimension is 3794 but corresponding boolean dimension is 7587

![cp error](https://user-images.githubusercontent.com/62559939/93234276-16c6f680-f74a-11ea-851b-62c17f197f06.png)

The files and pipeline are located here:
https://www.dropbox.com/sh/vtii2t5r39uu8rp/AAAeaZF7piK2RBETmObOwr7ma?dl=0

**Comment by DavidStirling** [comment]
Hi @sjmurphy1994,

It looks like you have 3 images of different sizes: 3740x1897 (1), 7479x3794 (2) and 14958x7587 (3). In your pipeline you resize image (1) to match image (3), but then try to apply this as a mask to image (2). The operation fails because the sizes do not match. You may therefore want to set up a resize module to target the size of image (2) instead.

These are vary large images to begin with, so you may find it smoother to use the 'nearest neighbor' resampling method, at least for testing.
