### ISSUE TITLE
Missing version number in macOS 4.0.3 and 4.0.4 releases 

### ISSUE THREAD

**Issue by suschizu** [CellProfiler/CellProfiler#4250]
Since version 4.0.3 the app doesn't show a version number anymore
the 	 `<key>CFBundleShortVersionString</key>` of Info.plist is missing and the `<key>CFBundleVersion</key>` still contains `<string>4.0.0</string>`

![Screenshot 2020-09-17 at 16 36 41](https://user-images.githubusercontent.com/16004333/93486938-0ad36400-f905-11ea-9449-f11c79385a6c.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX 14.6]
 - CellProfiler Version [e.g. 2.2, 3.1.9]
 - Downloaded from the website or installed from source?
 - If the latter, how?

**Additional context**

**Comment by bethac07** [comment]
Good catch, thanks! I'll add the short version key today, and we'll look into for future releases auto-editing the version in Info.plist so it doesn't need to be manually bumped.

**Comment by core-code** [comment]
i can confirm that the 'CFBundleVersion' of the 4.0.4 release is set to 4.0.0 and the 'CFBundleShortVersionString' is missing completely. thanks for working on this!

**Comment by core-code** [comment]
i can confirm that this is more or less solved in release 4.0.5

however, only the 'CFBundleVersion' reads 4.0.5, while the 'CFBundleShortVersionString' is at 4.0

that means the correct version number is only shown in Quick Look, but not in Column View or Get Info.

the 'Short' in 'CFBundleShortVersionString' doesn't mean it should only show the major version. its just because back in 2001 there was also 'CFBundleLongVersionString' but this hasn't really been used. all Apple apps definitely have 3 digits in their 'CFBundleShortVersionString'

thanks in any case for the improvement here
