### ISSUE TITLE
Adjust contrast on overlay image breaks 3D viewer

### ISSUE THREAD

**Issue by pearlryder** [CellProfiler/CellProfiler#4260]
When I adjust the contrast on a 3D image that has an overlay using the log normalization factor, the overlay disappears and the 3D slice scrolling no longer works to move between different slices.

**To Reproduce**
Run the 3d_monolayer_final pipeline from the [3D segmentation tutorial](https://github.com/CellProfiler/tutorials/tree/master/3d_monolayer). 

Adjust the contrast on an image that has an overlay using the log_normalized mode by changing the Normalization Factor and hit OK. Scrolling no longer works or overlay is not shown.

**Expected behavior**
I expected to be able to adjust the contrast on the underlying image with the overlay continuing to be shown over top at the same opacity as set.

**Desktop (please complete the following information):**
 - OS: Mac OSX 15.6
 - CellProfiler Version 4.0.4 from website

**Comment by DavidStirling** [comment]
To add to this, the issue here turns out to be about normalisation failing rather than the 3D viewer itself.

```Traceback (most recent call last):
  File "cellprofiler\gui\figure\_figure.py", line 1078, in on_int_entry
  File "cellprofiler\gui\figure\_figure.py", line 1102, in apply_contrast
  File "cellprofiler\gui\figure\_figure.py", line 1192, in refresh_figure
  File "cellprofiler\gui\figure\_figure.py", line 2093, in normalize_image
  File "matplotlib\cm.py", line 271, in to_rgba
ValueError: Floating point image RGB values must be in the 0..1 range.```

Currently we don't support normalizing colour images such as overlays. We expect cases where normalization settings can exceed matplotlib's supported display range, without those settings being necessarily invalid. We should probably make it so that you can't save a contrast adjustment if the normalization failed to render an image.
