### ISSUE TITLE
MeasureImageQuality error using calculate blur metrics

### ISSUE THREAD

**Issue by ehildebr** [CellProfiler/CellProfiler#4271]
I'm getting an error when trying to calculate blur metrics on images using MeasureImageQuality. It could possibly be something with the image, but the terminal report makes me think it might be a bug? Thanks!

Here is the terminal report: 
```
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  5 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
Failed to run module MeasureImageQuality
Traceback (most recent call last):
  File "cellprofiler\gui\pipelinecontroller.py", line 3348, in do_step
  File "cellprofiler_core\pipeline\_pipeline.py", line 1275, in run_module
  File "cellprofiler\modules\measureimagequality.py", line 1067, in run
  File "cellprofiler\modules\measureimagequality.py", line 1090, in run_on_image_group
  File "cellprofiler\modules\measureimagequality.py", line 1405, in calculate_power_spectrum
  File "scipy\linalg\basic.py", line 1223, in lstsq
ValueError: illegal value in 4-th argument of internal None
```

And screenshot of CellProfiler pipeline:

<img width="1260" alt="cellprofiler_settings" src="https://user-images.githubusercontent.com/29208535/94865519-bd2e1f80-040b-11eb-982a-994ceaf207a9.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellProfiler Version 4.05
 - Downloaded from the website

**Comment by DavidStirling** [comment]
Hi, we've not been able to replicate this. Would you be able to upload a copy of the pipeline and a problem image set? Thanks

**Comment by gzzwjhzxh** [comment]
Hi, @ehildebr, I'm getting same error as you on CellProfiler 4.07.  My pipeline can run on the Windows 10 Home Edition operating system, but this error occurs when the pipeline is running on the Windows 10 Professional Edition operating system. I doubt that this error is related to the computer operating system. Is your computer operating system also Windows 10 Professional?

**Comment by DavidStirling** [comment]
I've done some further digging here, and I think it's related to scipy/scipy#12747 and numpy/numpy#16744 in that this is the result of an underlying issue with mathematics libraries on Windows 10 versions updated past build 2004. We'd resolved the Numpy problem by pinning to 1.19.3, but it looks like the Scipy-related functions are still being effected. We'll have to see if these dependencies are updated to fix this.

**Comment by gzzwjhzxh** [comment]
@DavidStirling,  thank you for your reply!  It seems that this is a bug that cannot be fixed at present.  Unfortunately, that computer's operating system is Windows 10  version 2004.  And I cannot reinstall the system on that computer because it is public. It seems I have to use CP3.1.9 for analysis. Maybe I also need to confirm whether I will get different results from other versions of the window system, if I use CP 3.1.9 to analyze the image on Windows 10 version 2004.

**Comment by DavidStirling** [comment]
If you really want to use CP4, one thing you could try is building from source and installing `Numpy+MKL` from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy).

**Comment by gzzwjhzxh** [comment]
Due to lack of programming experience, it is difficult for me to build pipelines from source code. But when this bug can be completely fixed Windows 10 version 2004, could you inform me on github or forum (https://forum.image.sc/t/cellprofiler-4-0-7-valueerror-during-run-of-module-measureimagequality/45655)?
Thanks!

**Comment by DavidStirling** [comment]
I didn't mean building the actual pipelines, "building from source" means installing CellProfiler from the original code rather than using the packaged bundle. There are instructions for this. A source build allows you to change which sub-packages are installed and thus potentially work around the bug. Nonetheless I understand that this can be daunting without experience with Python.

I believe 3.1.9 should work because it uses a different (older) mathematics library. The results will probably be slightly different since several modules were updated in 4.0, but the general pipeline should work as intended. It's still best to not compare data from different CellProfiler versions though.

Hope that helps

**Comment by gzzwjhzxh** [comment]
Thank you so much for your patient explanation! Sorry, maybe my words is ambiguous, I mean if I use CP 3.1.9 to analyze the image on a computer with Windows 10 version 2004, whether the data I get will be different from that  I get from other computers with old version  Windows 10.  My preliminary tests have shown that the data from computers with different versions Windows 10 are the same. But I still hope that your team could completely fix this bug in later versions of CellProfiler if some sub-packages have been updated to fix this.

**Comment by DavidStirling** [comment]
Ah, ok. Which version of Windows 10 you use should not have any impact on the results from 3.1.9.

In terms of a resolution, we'll have to see when either Windows itself or the numerics library receives an update fixing this. If this doesn't happen soon there may be a couple of other things I could try.

**Comment by gzzwjhzxh** [comment]
I have started to analyze my images on CP 3.1.9. And I hope I can get meaningful data to complete my project. 

Generally speaking, for those who lack professional knowledge of image analysis, CellProfiler is a software that can obtain large amounts of data and realize automatic analysis. Thanks to all CellProfiler developers!

**Comment by DavidStirling** [comment]
Just an update on this, Microsoft have now released [KB4598291](https://support.microsoft.com/en-us/topic/february-2-2021-kb4598291-os-builds-19041-789-and-19042-789-preview-6a766199-a4f1-616e-1f5c-58bdc3ca5e3b?ui=en-us&rs=en-us&ad=us) which should fix this issue.
