### ISSUE TITLE
Cellprofiler won't open on Mac OS 10.15.7 (19H2)

### ISSUE THREAD

**Issue by MichaelSunJK** [CellProfiler/CellProfiler#4290]
I have trouble to open cellprofiler 3.1.9 and 4.0.5 version on MacOS 10.15.7. The programme close itself without any error message. I updated my java JDK but won't solve the problem. I also downloaded and installed JDK 1.8.0_152 but problem persist.

**Comment by DavidStirling** [comment]
Hi @MichaelSunJK,

Are you able to launch CellProfiler from the terminal? The command should be something like `open -na /Applications/CellProfiler.app`

**Comment by MichaelSunJK** [comment]
Hi! Yes I tried but with same result.

**Comment by DavidStirling** [comment]
Does any error appear in the terminal?

**Comment by MichaelSunJK** [comment]
No, no messages appeared.

**Comment by bethac07** [comment]
Yes, we've confirmed this on a teammate's machine also running 10.15.7, for whom built versions of CellProfiler previously worked and now do not after upgrading her OS.

We're going to work to dig into this, but since the change seems to be on Apple's end not ours, it may take a bit of time for us to sort out.

**Comment by alicelucas** [comment]
Hi @MichaelSunJK,
If you are still having problems with opening CellProfiler on MacOS 10.15.7, it could be helpful to take a look at those different workarounds we have found so far to get the application to open: https://github.com/CellProfiler/CellProfiler/wiki/Opening-CellProfiler-on-Mac-OS-10.15.7. 
Let us know if that works.
This issue is still under investigation and we will post here with updates.

**Comment by MichaelSunJK** [comment]
Hi! Thanks for the solutions!
I found another workaround by not putting Cellprofiler in the application folder, but under other folders(for example: Documents).

**Comment by xxqtony** [comment]
MscOS Big Sur version 11.6
Downloaded CellProfiler version 4.2.1
I got the error message as above, and copied below:
“CellProfilerB.app” can’t be opened because Apple cannot check it for malicious software

I've tried these ways:
1, rename it CellProfiler2 in Documents, Applications, or other places
2, In System Preferences -> Security & Privacy, clicked "Open Anyway"
3, right click and then open or direct double click
The same error always pop up when whichever method above or any combination is used
