### ISSUE TITLE
can't load modules from CP 3

### ISSUE THREAD

**Issue by SBata** [CellProfiler/CellProfiler#4298]
hi there

I downloaded the plugin folder and added the path to the CP 4 plugins.
however, when I try to load a pipeline that contains the `MeasureObjectIntensity Multichannel` from (https://github.com/BodenmillerGroup/ImcPluginsCP) I get the following error:

```
Error while loading MeasureObjectIntensity Multichannel: Could not find the MeasureObjectIntensity Multichannel module
Do you want to stop processing?
```
any suggestions?

I posted mistakenly here (https://github.com/BodenmillerGroup/ImcPluginsCP/issues/40) but I thought it would fit better here

![image](https://user-images.githubusercontent.com/10268015/97249987-608c0d80-17db-11eb-9238-afc39b34ac37.png)

 - OS: OSX 10.14.6]
 - CellProfiler Version 4
 - Downloaded from the CP website

**Comment by bethac07** [comment]
Hi, 

Those aren't our plugins, so that repository is in fact the correct place for letting them know.  I know Vito has been working on getting some of them to support CellProfiler 4; if you want to help him out, you can follow our [3 to 4 plugin migration guide](https://github.com/CellProfiler/CellProfiler-plugins/wiki/CellProfiler-3-to-4-migration-guide).  Closing here.

**Comment by votti** [comment]
Actually the plugins are all now working with Cellprofiler 4 in the development branch (https://github.com/BodenmillerGroup/ImcPluginsCP/tree/develop-cp4)  - the only thing lacking is proper release notes for which I hope to find time soon :)

Cheers, Vito

**Comment by SBata** [comment]
issue solved with the CP4 plugins linked by Vito
