### ISSUE TITLE
CP_JAVA_HOME on Windows should be system scope

### ISSUE THREAD

**Issue by imagejan** [CellProfiler/CellProfiler#4320]
**Describe the bug**
Currently, the `CP_JAVA_HOME` environment variable is set upon installation (of CellProfiler 4.0.*) as a *user variable*, whereas it should be set as a *system variable* to be available to all users (in line with the desktop shortcut).

I think the relevant lines are here:
https://github.com/CellProfiler/distribution/blob/18e19b1a2e81f0cd571013a3a427bf055a9cfb7b/windows/CellProfiler.iss#L47-L48

... where `HKCU` should be replaced by `HKLM` (`HKEY_LOCAL_MACHINE`) (and `Environment` replaced by `SYSTEM\CurrentControlSet\Control\Session Manager\Environment`) for a system variable.

**To Reproduce**
1. Install CellProfiler 4.0.7 on a multi-user Windows system (e.g. by user `user01` with admin premissions)
2. Sign out, and sign it as different user (e.g. `user02`)
3. Double-click on the newly created *CellProfiler* shortcut on the desktop.
4. Watch CellProfiler fail to find a valid Java installation...

**Expected behavior**
A system-wide installation of CellProfiler should be runnable by any user account without error messages.

**Desktop**
 - OS: Windows 10
 - CellProfiler Version: 4.0.7
 - Downloaded from the website

**Comment by DavidStirling** [comment]
Thanks, I've also encountered this. I think a better solution would be to migrate away from requiring `CP_JAVA_HOME` at all when running a frozen build. At present the presence of `CP_JAVA_HOME` is used as a check for whether to try using the java folder in the CellProfiler installation directory (and it's path is only then considered if the builtin java folder is absent). In a future update I'd like to only have the variable inspectedwhen said java folder is absent - not doing it like this in the first place was my mistake.

The new system I imagine would be as follows:
- First check for a java folder in the app directory.
- If it's absent, check for `CP_JAVA_HOME`.
- If that's absent or incorrect, check for `JAVA_HOME`. 

This should allow us to avoid setting the environment variable on install, which might also help because CP3 also needs the same variable and it might be best to not overwrite it when installing CP4.

**Comment by imagejan** [comment]
Thanks @DavidStirling for the info. That sounds reasonable.
