### ISSUE TITLE
Module improvement: TAS texture features and RWC co-localization measurement

### ISSUE THREAD

**Issue by tilenkranjc** [CellProfiler/CellProfiler#4328]
I met @AnneCarpenter in 2015 at ELMI in Spain and she invited me to contribute two plugins I wrote for CP. Now, after 5 years, I'm ready to do it =). 

The two plugins are currently in my [repo](https://github.com/tilenkranjc/cellprofiler-plugins) and as you can see they haven't been updated in a while. I'm happy to contribute the code to CP.

* MeasurementTAS calculates [TAS texture features](http://www.biomedcentral.com/1471-2105/8/110/). This can be added to MeasurementTexture module.
* MeasurementRWC calculates [Rank Weighted Coefficient](http://www.biomedcentral.com/1471-2105/12/407/). It's a co-localisation metrics that takes into account both the intensities and locations of pixels in both channels. It usually gives a better idea of co-localisation than commonly used methods.

I'm happy to integrate the code in the existing plugins if there's still interest for this. Please let me know.

**Comment by AnneCarpenter** [comment]
Great! I hope others can comment on the right destination - the plugins folder or integrate into an existing module to get this headed in the right direction.

**Comment by bethac07** [comment]
Hi! Thanks for contributing your code.  We're always excited when the community wants to get involved!

The MeasureColocalization module actually already calculates the RWC, so that one is already in!

For the TAS, we'd typically ask people to contribute it to the [plugins repository](https://github.com/CellProfiler/CellProfiler-plugins).  Does that work for you?

Thanks again!

**Comment by tilenkranjc** [comment]
Great, I haven't used coloc module in a while, so I haven't noticed that. I'm glad it's in there!

For TAS I'll open a pull request in plugins repo.
