### ISSUE TITLE
CellProfiler v4.1.3 IlluminationCorrection Apply does not work with "Median Filter" smoothing method.

### ISSUE THREAD

**Issue by citypalmtree** [CellProfiler/CellProfiler#4369]
Hi,

I am trying to use IlluminationCorrection Calculate/Apply modules on CP4, but selecting "Median Filter" for the smoothing method with 100 smoothing filter size causes the CP4 stall (rather, it just does not proceed).
Here is the screenshot of CP4 where it just stalls:
![cp error](https://user-images.githubusercontent.com/67493535/111927746-2cfe9800-8a88-11eb-869f-925d9423cf93.PNG)

Here is a set of images that I am using:
[images.zip](https://github.com/CellProfiler/CellProfiler/files/6178789/images.zip)

Here is the pipeline that I am using:
[pipeline_error.zip](https://github.com/CellProfiler/CellProfiler/files/6178801/pipeline_error.zip)

I am currently trying to use the modules with the Python packages, but couldn't get it to work.
I, then, tested it on Windows CP4, not working.
I tried it on CP3, and it works.

Any help would be greatly appreciated!

**Comment by DavidStirling** [comment]
Hi @citypalmtree,

Between CP3 and CP4 the underlying implementation of this filter was updated (we use the scikit-image median filter functions). The pipeline you have does work, but it's appearing to hang because there's a severe performance hit as you increase the size of the new median filter. Generally we advise against using very large structuring elements with median filters.

However, perhaps we could improve things a little. It might be worth us taking a look at the rank version of the filter as an alternative. This will need further investigation to avoid recreating issues like that in #2898. From a quick test, the rank version seems to be slower with a small window but much faster with a large one. We'd need to check whether the output is the same.

```
Size 5: filters.median completed in 2.49s
Size 5: filters.rank.median completed 1.82s
Size 50: filters.median completed 54.17s
Size 50: filters.rank.median completed 3.05s
```

We could also take a look at the native scipy filters, which we use elsewhere - see #4182
