### ISSUE TITLE
Identify Secondary Objects show negative value for %Area covered by objects (for very large images)

### ISSUE THREAD

**Issue by NasimJ** [CellProfiler/CellProfiler#4374]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce, including an attached/linked image set and pipeline, may be closed without investigation. You may delete this section before posting your issue below.
---

**Describe the bug**
In IdentifySecondaryObjects module, when working with very large images (50 MB), in some threshold boundaries, shows a negative value for the area covered by the objects.
When setting the lower and upper bound threshold at 0.0012 to 0.002, a negative % area covered by the objects was observed (screenshot: AreaCov_Neg), but when increased the upper bound to 0.008, for the same image, got a positive % (AreaCov_Pos). I've tested this for a couple of images in this data set and all of them showed the same behavior. 
![AreaCov_Neg](https://user-images.githubusercontent.com/55710463/113624663-e84d3200-962d-11eb-9d72-81ef7f5bb132.png)

![AreaCov_Pos](https://user-images.githubusercontent.com/55710463/113624676-ed11e600-962d-11eb-9035-8c44c80aad67.png)

**To Reproduce**
For images and pipeline, please reach out to me, but in general, here are the steps:
1. Loaded a large image (I used LoadData module)
2. Applied Illumination Correction
3. Calculated and applied background illumination correction
4. Identified Primary Objects from DNA channel (screenshot of method is attached)
5. Identified SecondaryObjects

![IdSecondary](https://user-images.githubusercontent.com/55710463/113624703-f56a2100-962d-11eb-88d5-38c71f4b47d7.png)

**Expected behavior**
An expected behavior is having a positive number for the Area covered by objects.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 
 - CellProfiler Version 4.1.3
 - Downloaded from the website or installed from source? from Website
 - If the latter, how (cloned, installed from pypi, etc)?

**Additional context**

**Comment by bethac07** [comment]
I've tried the image set in question on 4.1.3 built, 4.2.1 source, and master source, and can't reproduce - I will admit I'm using un-illumination-corrected images, but I really can't see why that should matter, and I'm otherwise copying the IDSecondary settings exactly. 

Ultimately, this is just a display metric, it isn't saved or used for anything other than the user's own convenience, so I'm not sure it's worth spending a ton more energy tracking this down (is it a package version, OS version, etc). Can reopen if and when we find it again!
