### ISSUE TITLE
Error with ExportToSpreadsheet module when running CellProfiler with command line

### ISSUE THREAD

**Issue by vani-by** [CellProfiler/CellProfiler#4390]
**Context**
I am using a CellProfiler docker image to run two pipelines with command lines. The docker image is available here: https://hub.docker.com/r/cellprofiler/cellprofiler. On this docker image, CellProfiler version is 4.0.6 (but my pipelines are designed with CellProfiler 4.1.3)
My project requires two pipelines: an illumination pipeline, which generate 5 illumination functions (.npy format, on file per channel), and an analysis pipeline, which generate a csv file with all measurements realized by the pipeline on my images. Running the illumination pipeline works fine, but I have a problem when running the analysis pipeline. 

**My command line**
_sudo docker container run -it -v /home/s3raw:/s3raw -w /s3raw cellprofiler/cellprofiler -c -p /s3raw/AnalysisPipelines/analysis_pipeline.cppipe -o /s3raw -i /s3raw/AllImages_

I precize that .npy files that are expected to run the analysis pipeline are in the same inout folder than my input image (i.e. /s3raw/AllImages)

**My analysis pipeline**
![image](https://user-images.githubusercontent.com/83637014/116979675-9566a900-acc5-11eb-9735-d028061283a5.png)

**Describe the bug**
When I run my command to run my analysis pipeline, I get this problem: 
![image](https://user-images.githubusercontent.com/83637014/116978409-f7beaa00-acc3-11eb-9ee8-d655cb10bf27.png)

**What I tried**
I tried with a docker image with a previous version of CellProfiler (3.1.9) but I have the same problem. I have already checked that the wxPython module is installed in my docker and it is the case (version 4.1.0). 

For the time being, I use export measurements using the "ExportToDatabase" module but it would be simplier for me to export a csv file. What can be done to fix my problem ?

**Comment by bethac07** [comment]
This was an issue in 4.0.6 that was[fixed in 4.0.7](https://github.com/CellProfiler/CellProfiler/pull/4307), so you can use either the 4.0.7 or 4.1.3 Docker and shouldn't have this issue.  In general, though, if you're making pipelines in 4.1.3, I would strongly advise you to use that Docker version, otherwise anything that changed in 4.1.3 vs 4.0.6/7 is not going to behave the way that you expect in your Docker (and may cause your analysis run to stop/fail).

Closing since this is known to already be fixed.  Please do reach out if something else isn't working the way you expected!
