### ISSUE TITLE
FlagImage crashes when 'Ignore flag skips on last cycle' is enabled.

### ISSUE THREAD

**Issue by DavidStirling** [CellProfiler/CellProfiler#4442]
I've been getting the following error when attempting to run analysis with this module enabled:

```
Worker 0: Tue Aug  3 17:55:34 2021: Image # 105, module Groups # 4: CPU_time = 0.00 secs, Wall_time = 0.00 secs
Worker 0: Running module FlagImage 5
Worker 0: Error detected during run of module FlagImage#5
Worker 0: Traceback (most recent call last):
Worker 0:   File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cellprofiler_core\pipeline\_pipeline.py", line 1161, in run_image_set
Worker 0:     self.run_module(module, workspace)
Worker 0:   File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\cellprofiler_core\pipeline\_pipeline.py", line 1298, in run_module
Worker 0:     module.run(workspace)
Worker 0:   File "c:\users\administrator\documents\github\cellprofiler\cellprofiler\cellprofiler\modules\flagimage.py", line 568, in run
Worker 0:     statistics += self.run_flag(workspace, flag)
Worker 0:   File "c:\users\administrator\documents\github\cellprofiler\cellprofiler\cellprofiler\modules\flagimage.py", line 737, in run_flag
Worker 0:     if self.ignore_flag_on_last and (m.group_length - m.group_index) == 0:
Worker 0: AttributeError: 'Measurements' object has no attribute 'group_length'
Progress Counter({'Unprocessed': 7980, 'InProcess': 2379, 'FinishedWaitingMeasurements': 813})
Cancelled!
```

Looks like `group_length` wasn't recorded correctly. The input images are all sourced from a single .czi file, so I'm not sure if that could be related?

**Comment by callum-jpg** [comment]
This error seems to have originated when core was split from CellProfiler. During this split phase, the "Ignore flag skips on last cycle" feature was added to FlagImage (CellProfiler/CellProfiler#3876) but the setting of group_length was not carried over entirely.

For example, when test mode is run, group_length is set in [pipelinecontroller.py](https://github.com/CellProfiler/CellProfiler/blob/master/cellprofiler/gui/pipelinecontroller.py) in CellProfiler. However, this requires methods in core [_measurements.py](https://github.com/CellProfiler/core/blob/master/cellprofiler_core/measurement/_measurements.py) which were removed during the core split (I think). Previously, in CellProfiler/CellProfiler#3876, methods to set group length were found in [cellprofiler/measurement.py](https://github.com/CellProfiler/CellProfiler/blob/69a02b14d82670dd8435dd27c1f88102d4a11a42/cellprofiler/measurement.py) Adding `set_group_length`, `get_group_length` and `group_length = property(get_group_length, set_group_length)` back to core [_measurements.py](https://github.com/CellProfiler/core/blob/master/cellprofiler_core/measurement/_measurements.py) solves the FlagImage for running in test mode only.

When analysis mode is run, group_length should be set in [core/_pipeline.py](https://github.com/CellProfiler/core/blob/master/cellprofiler_core/pipeline/_pipeline.py) as originally set in CellProfiler/CellProfiler#3876 but has been removed when splitting CellProfiler and core. However, adding group_length to the image object in [core/_pipeline.py](https://github.com/CellProfiler/core/blob/master/cellprofiler_core/pipeline/_pipeline.py) does not solve this issue as you may expect. _pipeline.py is only in the codepath to be run when an input module is changed. Loading a pipeline and not changing anything in the input modules (and, presumably like with LoadData but I haven't tested this) leads to a group_length error. However, if you choose yes to extract metadata and then switch it back to no then group_length is correctly set since _pipeline.py is called. Thus, the solution for this bug should be to update core/_measurements.py and core/_pipeline.py to have group_length set and to also include _pipeline.py to be run upon analysis, independent of the input modules.

**Comment by bethac07** [comment]
@callum-jpg Can you put exactly which code change you tried here? Is it on a branch I can checkout? 

>However, adding group_length to the image object in [core/_pipeline.py](https://github.com/CellProfiler/core/blob/master/cellprofiler_core/pipeline/_pipeline.py) does not solve this issue as you may expect.

**Comment by callum-jpg** [comment]
The changes mentioned above can be found on the [core 4442 branch](https://github.com/CellProfiler/core/tree/issues/%234442)
