### ISSUE TITLE
CalculateMath module outputting incorrect value

### ISSUE THREAD

**Issue by MCF10A** [CellProfiler/CellProfiler#4540]
Please include all requested information- reports without specification of OS/Version information or without SPECIFIC information on how to reproduce, including an attached/linked image set and pipeline, may be closed without investigation. You may delete this section before posting your issue below.
---

**Describe the bug**
When using the CalculateMath module, it is outputtting a value different to when I do it by hand. The operation is taking the reciprocal of a mean Area measurement (by raising to -1), then multiplying by 100000 to give a reasonably sized value. After checking each step, it seems to be the reciprocal step that causes the issue. 

**To Reproduce**
1. Obtain a mean Area measurement with the MeasureObjectSizeShape
2. Using the CalculateMath module, raise this Area to -1 and multiply by 100000. (Screenshots below)
3. Output value will be different than if done with a calculator by hand.

**Expected behavior**
I expect that the value should be correct. 

**Screenshots**
![image](https://user-images.githubusercontent.com/104208871/164722563-3b029906-1925-4a60-8579-a36dc1dc8dee.png)

**Desktop
 - OS: Windows 10
 - CellProfiler Version 4.2.1
 - Downloaded from the website

**Comment by bethac07** [comment]
Hi,

Is this possibly an order of operations issue? What you are using here is not actually a per-image mean measurement of Areas, but each individual object's area; the module display shows a per-image mean for sake of compactness, but it's actually operating on each individual value. Taking the inverse of the mean of the set will give you a different value than taking each value's inverse and then taking the mean - see a short example below. If you DID want to calculate the per-image mean area, so that then you could run a calculation on it, you could run the MeasureImageAreaOccupied module to get the total area of all of your objects and then divide it by the count of your objects to get a per-image mean-object-area that you could then further do this calculation.

I hope that helps!

```
>>> import numpy
>>> a = numpy.array([1,5,7,8,122])
>>> numpy.mean(a)
28.6
>>> numpy.mean(a)**-1
0.03496503496503496
>>> numpy.mean([float(x)**-1 for x in a])
0.2952107728337236
```
