### ISSUE TITLE
How to set channels for cellprofiler cppipe file?

### ISSUE THREAD

**Issue by semir2** [CellProfiler/CellProfiler#4557]
Hi,
     Thanks for your great tools with cellprofiler. I am fresh man using it and I have some problems with pipeline. [Image-iT™ Cell Painting Kit](https://www.thermofisher.cn/order/catalog/product/I64000?SID=srch-hj-I64000)  have been used in my expriment whith Opera Phenix machine, as we know, we 5 channels(MainExcitationWavelength:568, 630, 365, 475, 550, 475) with 6 dyes (Phall, MCTracker Deep Red, HOECHST 33342, PhenoVue Fluor 488, WGA, SYTO14) have been set in cellprofiler pipeline,  6 tif images have been got for every fields of view. which image should I chose for 5 channels(DNA, ER, RNA, AGP, Mito) as input for cellprofiler tools. which channel should I chose for AGP? Channel 1 or channel 5?

![图片](https://user-images.githubusercontent.com/46958122/174107699-1c4d29b4-8042-4526-9542-c7800addd06f.png)

As showed figutue, do is right for my cell painting pipeline?

Many thanks

**Comment by bethac07** [comment]
Hi,

The AGP channel in the standard pipeline shows both the Phalloidin and WGA staining - realistically, those dyes cannot be spectrally separated on most standard systems. If you want to (and can successfully on your system) capture them as separate spectral channels, you'll then need to modify your pipeline to have different channels. 

Hope that helps! Since this isn't about the software specifically, will close here, but please do feel free to follow up on forum.image.sc. Thanks!

**Comment by semir2** [comment]
> 
Many thanks！
