### ISSUE TITLE
wxPython conflicts during installation

### ISSUE THREAD

**Issue by jessijessi** [CellProfiler/CellProfiler#4565]
**Informations:**
 - Operative system: CentOS Linux 7 (Core)
 - CellProfiler Version 4.2.1
 - Installation method: Installed from source throught pip and conda, and finally I try also to install from github repository

**Description of the issue:**
The installation failed probably because there are conflicts in the installation of wxPython. The problem might to be that CellProfiler request Python>3.8 instead wPython seem to request Python<3.6. 

**Error messages**
The final part of the error that I is below in the screenshoot:

<img width="594" alt="eroor_cellprofiler" src="https://user-images.githubusercontent.com/72512371/178704237-8ab84712-3965-4b1a-9110-8775e937558d.png">

How could I fix?

Thank you,
Best regards

**Comment by bethac07** [comment]
This seems to be a CentOS7 specific issue; the [wxPython wheels are only provided for that OS through Python 3.6](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/centos-7/), whereas on most other OS's it provides 4.1.0 (the current pinned version in CellProfiler) through [Python3.8](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/) . 

Unfortunately, the only way I can think of you'll be able to fix this on CentOS7 is to work on getting your wx building correctly - in the screenshot above, it looks like your GTK is missing. You may find [this post](https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html) helpful in figuring out what packages you need before trying to build wx. 

Closing here because this isn't a CellProfiler issue per se; the post I linked above has links in the sidebar to both the wxPython GitHub and Discourse forum, where if the blog post instructions don't work hopefully someone will be able to help out. Best of luck!
