### ISSUE TITLE
Test Mode & Analyze Images Doesn't Work with my Pipeline

### ISSUE THREAD

**Issue by svalathappan** [CellProfiler/CellProfiler#4611]
I created a pipeline and saved my project as a .cpproj file on Thursday. I was able to run the project on Thursday with no problems whatsoever. Coming back to it on Monday I found that I could not run/test the project anymore.
---

When I check to make sure the pipeline is working, I see all green check marks on the left side. however, I cannot get it to run test mode or analyze my image set.

**To Reproduce**
1. I click "Start Test Mode" or "Analyze Images"
2. Nothing happens :(

**Expected behavior**
I expected it to analyze the images, which would result in a fan of windows popping up, as well as the computer screen showing each of the steps highlighted as they are being done. If it was in "analyze images" mode, I would also see the data I want saved in my computer folder.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellProfiler Version 4.2.1
 - Downloaded from the website

**Comment by bethac07** [comment]
Hi,

Sorry to hear that!

1) Is there any chance your images have moved since you last ran this, like maybe you renamed the folder or put them in a new subfolder? Are they maybe on an external drive?
2) Whether or not that is true, if you clear the images from your project and then re-add them and try to run, can you?

**Comment by svalathappan** [comment]
Thank your for your reply!
1. I haven't moved the images, but they are on a USB, connected to the computer unit. I have tried moving it to a folder under the Users location, but that hasn't worked either.
2. I did try this several times, but to no avail. I added new image types (I used .tif then tried .nd2) but it gave me the same result

**Comment by bethac07** [comment]
Hmm! Are you able to run the example pipeline from the welcome screen?

When you look at your NamesAndTypes module, does it say you have image sets successfully created?

**Comment by svalathappan** [comment]
I'm able to run the example pipeline. When I try to update the current settings on NamesAndTypes, it says I don't have any image sets available. I do have 3 .tif files in the Images module though.

**Comment by bethac07** [comment]
Ok! That sounds then like your CellProfiler is working, it's just that your files aren't assorting into image sets properly. If your original NamesAndTypes module expected ND2s, it's maybe not surprising that the TIFs aren't also forming correct image sets; I also suspect that maybe it's that you haven't re-extracted Metadata headers on the new ND2s. 

I'm going to close this here, because it isn't a CellProfiler bug per se; I think you might find this [blog post](https://carpenter-singh-lab.broadinstitute.org/blog/input-modules-tutorial) and the accompanying YouTube video helpful, if not then we can discuss in your [forum post](https://forum.image.sc/t/test-mode-analyze-images-doesnt-work-with-my-pipeline/70525)
