### ISSUE TITLE
Dark Mode enabled but buggy with wxPython 4.2.0

### ISSUE THREAD

**Issue by gnodar01** [CellProfiler/CellProfiler#4632]
**Describe the bug**
CellProfiler, when using the newly released [wxPython 4.2.0](https://wxpython.org/news/2022-08-07-wxpython-411-release/index.html) has dark mode (enabled when the computer is set to dark mode in system settings). This is actually the result of wxPython 4.2.0 being built on the recent [wxWidgets 3.2.0 release tag](https://www.wxwidgets.org/news/2022/07/wxwidgets-3.2.0-final-release/), which includes native dark mode on macOS. It mostly works well out of the box, but there are some UI elements that don't work well with it. In particular, the Grid in NamesAndTypes (`imagesetctrl.py -> ImageSetGridTable`) is unreadable. The welcome screen works fine, but still has an all white background.

**To Reproduce**
1. `pip install wxpython==4.2.0`
2. Enable dark mode in system preferences
3. Open CellProfiler

**Screenshots**
In general it looks good:
<img width="1185" alt="Screen Shot 2022-08-29 at 3 51 24 PM" src="https://user-images.githubusercontent.com/8888732/187286380-9e7794de-2a97-4abd-9f61-4cf7e5465ba4.png">

But the Grid background in NamesAndTypes is all white, with the text too light to see:
<img width="1184" alt="Screen Shot 2022-08-29 at 3 51 47 PM" src="https://user-images.githubusercontent.com/8888732/187286532-45a53a6d-9462-4f4d-816f-783566391401.png">

<img width="1180" alt="Screen Shot 2022-08-29 at 3 52 01 PM" src="https://user-images.githubusercontent.com/8888732/187286560-45e03621-8719-4ea9-88e9-c6a790dada2e.png">

Other grid elements work fine out of the box:
<img width="1184" alt="Screen Shot 2022-08-29 at 3 54 28 PM" src="https://user-images.githubusercontent.com/8888732/187286750-2a87ecd8-0a5b-443a-896d-2e6492b57cc6.png">

The welcome screen is styled the same as in light mode:
<img width="1185" alt="Screen Shot 2022-08-29 at 3 52 10 PM" src="https://user-images.githubusercontent.com/8888732/187286634-0874e735-bc28-4471-8dc0-9e68b56fbdbb.png">

**Desktop (please complete the following information):**
 - OS: MacOs 12.5.1, Intel (but same behavior exists on M1 macs, where users are more likely to have wxPython 4.2.0, since we instruct them to do so in the wiki)
 - CellProfiler Version: >= 4.2.4 (with wxPython >= 4.2.0)
 - Downloaded from the website or installed from source? Both.
 - If the latter, how (cloned, installed from pypi, etc)? Cloned, but with override of current default of wxPython == 4.1.0

**Additional context**
Haven't done an exhaustive check, but all other gui elements look good. There may be some I didn't spot that also need to be cleaned up.

**Comment by bethac07** [comment]
Interesting- the welcome screen works for you? It definitely does not for me (and hasn't with any version of wx since 4.1.0 - 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/6721515/187496503-31261d7d-03cd-4804-8dd7-c09c4577021a.png">

**Comment by DavidStirling** [comment]
A little bit of info since I've also encountered this -

It would appear that some source installs of wxPython, mine included, don't properly detect MacOS light/dark mode. In these cases calling `wx.SystemSettings.GetAppearance().IsDark()` will always return `False`. The `wx.EVT_SYS_COLOUR_CHANGED` events are being triggered when the system theme switches and propogate as expected, so wx is at least aware that the system theme updated. Perhaps there's a fault in the IsDark logic somewhere so it's always thinking that the system theme is light, which would explain the lack of dark mode.

A test might be to try running the dark-mode source install and see if `IsDark()` returns `True`. If so it probably means that something in the environment is interfering with it as Nodar suggested. What's promising is that wx is at least notified when the system theme changes.

**Comment by DavidStirling** [comment]
So writing that up gave me some ideas, and I found the problem:

Python binaries originally built against MacOS versions prior to 10.15 lack the Info.plist key which defines whether the app should respond to theme switches. When this key is missing MacOS assumes the app should be pinned to the 'light' theme.

Finding `Python.app` that your source install is running from and adding the following to the Info.plist should get dark mode (and IsDark) working:

```
	<key>NSRequiresAquaSystemAppearance</key>
	<string>false</string>
```

That's not a fantastic solution, but making sure that a newer build of Python is used for packaging should eliminate the problem for the average user, and I expect this was already the case.

**Comment by gnodar01** [comment]
Thanks @DavidStirling, I did read about the plist property before, but it didn't occur to me to put it into python.app's Info.plist. That worked well.

@bethac07 For users that are using CellProfiler from source, and have conda's pre-built python3.8, we could give instructions on how to modify the Info.plist file, or on how to get a system built framework version of python with the property already in place, but the last thing I want is to add additional steps into installing CellProfiler from source.

**Comment by bethac07** [comment]
>but the last thing I want is to add additional steps into installing CellProfiler from source.

Totally with you on that, but if the thing is - "if you are using CellProfiler in Mac AND from conda AND you want dark mode, do this, otherwise live with light mode", I think it's totally fine to put out the instruction - if you don't want to do it, you're no worse off than you are now, and it's not a "mandatory" thing that anyone installing from source needs to do.
