### ISSUE TITLE
source code installation JVM problem

### ISSUE THREAD

**Issue by olasabet** [CellProfiler/CellProfiler#4869]
I was trying to follow the instructions for (Source installation (OS X and macOS)) despite it being difficult but I have a repeated error. 

First:  I am using macOS Ventura (version 13.6)
          MacOS 2019 (2.6 GHz 6-Core Intel Core i7)

After installing homebrew and OpenJDK this is what I get when I type (ls /Library/Java/JavaVirtualMachines/)
adoptopenjdk-8.jdk	openjdk-11.jdk		openjdk.jdk		temurin-11.jdk		temurin-18.jdk		temurin-8.jdk

I set my JAVA_HOME env variable as follows
.bashrc: export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-18.jdk/Contents/Home"
 source ~/.bashrc

I didn't have to install Python because I already had Python 3.9.15

I decided to go a global source installation (no conda env), therefore the next step was
brew install mysql

So far so good, problem starts wirth the next step (running CP from source)

I tried option 1 (pip3 install cellprofiler) and got ( I hope you can see my attachment), but in essence  (  Exception: JVM not found)
<img width="1791" alt="Screenshot 2024-02-09 at 00 05 42" src="https://github.com/CellProfiler/CellProfiler/assets/30659093/b7af8baa-f15c-45da-bc1e-b834a02bf2af">

I googled and searched and it seems I am not  the only one who was faced with that during installation, but the suggestions provided earlier (including brew install javabridge) did not work for me. Therefore I would appreciate some tips.

**Comment by gnodar01** [comment]
Can you try to point `JAVA_HOME` to `/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home` instead? After you set the variable start a new terminal session instead of calling `source ~/.bashrc`, and do `env | grep JAVA_HOME` to ensure it is set properly.

**Comment by olasabet** [comment]
Hi Nodar, ended up with the same error

**Comment by gnodar01** [comment]
Can you run `python -c "import os; print(os.environ['JAVA_HOME'])"` (or `python3` or `python39` depending on your setup) and confirm that the output is indeed `/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home`. If so try running `python -m pip install cellprofiler`. If not try running `JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home python -m pip install cellprofiler`. Again replace `python` with `python3` or `python39`, depending on whichever one points to the Python 3.9.15 you noted. You can run `python --version` to confirm.

**Comment by olasabet** [comment]
Hey, yes I got /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home so I followed it with your suggestion >> python -m pip install cellprofiler

For a change it did not complain about my JVM but I got a new error 

![Uploading Screenshot 2024-02-10 at 00.39.04.png…]()

**Comment by olasabet** [comment]
<img width="1968" alt="Screenshot 2024-02-10 at 00 46 15" src="https://github.com/CellProfiler/CellProfiler/assets/30659093/74b25847-2fee-4136-afdd-862a98b1d9b8">

**Comment by gnodar01** [comment]
Hmm, can you try:

`python3 -m pip install "numpy==0.24.4"`

`python3 -m pip install "Cython==0.29.36"`

`python3 -m pip install --no-cache-dir  cellprofiler`

**Comment by olasabet** [comment]
but before I do, just want to point out that I am trying to do this globally not in an env. Wouldn't downgrading my numpy package in that case be a bad idea?

**Comment by gnodar01** [comment]
> Either way are we sure about the numpy version

Sorry, I meant to type `python3 -m install "numpy==1.24.4"`.

> Wouldn't downgrading my numpy package in that case be a bad idea?

It very much depends on other libraries and tools you have installed globally, and what version ranges of `numpy` they require. From the perspective of `cellprofiler==4.2.6`, I know that `numpy==1.24.4` works well because its the version I have locally. However the actual requirement for `cellprofiler==4.2.6` is `numpy>=1.20.1`, so other versions, including whatever version you currently have, may work fine.

The caveat is `Cython`. The `Cython` package has a bit of a strange versioning scheme in that they went from `Cython==0.29.37` directly to `Cython==3.0.0`, skipping the `1.x.x` and `2.x.x` ranges. That particular version jump gave us a bit of trouble for `cellprofiler==4.2.6`. I know that `numpy==1.24.4` works fine with `Cython<3.0.0`, but I don't know what the upper bound is. In other words it may be that `numpy==1.26.4` (the latest version of `numpy`) would work fine with `Cython<3.0.0`, but I'm not certain.

We need `Cython` to build `python-javabridge` as well as `centrosome`, and `Cython` in turn has a soft reliance on `numpy`. Since both `centrosome` and `python-javabridge` failed to build in your screenshot, I'm hoping that pre-installing `numpy` and `Cython` with specific versions will help to alleviate that.

You may want to try `python3 -m pip install "numpy==1.26.4"` and just see if `pip` reports any dependency conflicts. If you already have some tool that has a dependency of `"numpy>1.26.4"` then `pip` will report that in the output.

**Comment by gnodar01** [comment]
Ah, yeah that's probably something to do with [this issue](https://github.com/PyMySQL/mysqlclient/issues/688).

Try downgrading `mysql` (which `mysqlclient` depends on).

`brew uninstall mysql`

`brew install mysql@8.0`

**Comment by gnodar01** [comment]
Hmm, `mysql==0.0.3` shouldn't be there. Did you do a `pip install mysql` instead of `brew install mysql`?

The `mysqlclient` version is also incorrect. `cellprofiler` hard pins it at version `1.4.6`.


We want:

`brew install mysql@8.0`

and 

`python3 -m pip install mysqlclient==1.4.6`

**Comment by olasabet** [comment]
I started fresh again and now if I pip freeze I only see my numpy and Cython packages 
Cython==0.29.36
numpy==1.24.4

I then installed mysql >> brew install mysql@8.0

and attempted to install mysqlclient >> python3 -m pip install "mysqlclient==1.4.6"

but again I got the same error of not finding mysql_config

![Screenshot 2024-02-12 at 23 09 08](https://github.com/CellProfiler/CellProfiler/assets/30659093/c8c5e10e-8a6c-4e2b-a445-df80a380106e)

**Comment by gnodar01** [comment]
Wow that's super aggravating. Sorry this has become so troublesome. I'd like to try one more thing, and if it fails it may be easier to set up a zoom call, if you're up for it, so that we can solve the problem quickly and we don't have to go back and forth over several days. If you'd rather not do a zoom call, I'm happy to keep debugging with you here.

If you run `which mysql_config`, my guess is that nothing comes up, is that correct?

When you did `brew install mysql@8.0`, you may have received a message similar to the following:

```
==> mysql@8.0: stable 8.0.36 (bottled) [keg-only]
Open source relational database management system
https://dev.mysql.com/doc/refman/8.0/en/
/usr/local/Cellar/mysql@8.0/8.0.36 (318 files, 301.2MB)
  Poured from bottle using the formulae.brew.sh API on 2024-02-12 at 18:25:38
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/m/mysql@8.0.rb
License: GPL-2.0-only with Universal-FOSS-exception-1.0
==> Dependencies
Build: bison ✘, cmake ✘, pkg-config ✔
Required: icu4c ✔, libevent ✔, libfido2 ✘, lz4 ✔, openssl@3 ✘, protobuf@21 ✔, zlib ✘, zstd ✔
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -u root

mysql@8.0 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have mysql@8.0 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/mysql@8.0/bin:$PATH"' >> ~/.zshrc

For compilers to find mysql@8.0 you may need to set:
  export LDFLAGS="-L/usr/local/opt/mysql@8.0/lib"
  export CPPFLAGS="-I/usr/local/opt/mysql@8.0/include"

For pkg-config to find mysql@8.0 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/mysql@8.0/lib/pkgconfig"

To start mysql@8.0 now and restart at login:
  brew services start mysql@8.0
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/mysql@8.0/bin/mysqld_safe --datadir\=/usr/local/var/mysql
==> Analytics
install: 3,480 (30 days), 7,767 (90 days), 13,065 (365 days)
install-on-request: 3,469 (30 days), 7,755 (90 days), 13,054 (365 days)
build-error: 90 (30 days)
```

The specific line that states: `echo 'export PATH="/usr/local/opt/mysql@8.0/bin:$PATH"' >> ~/.zshrc` is important. First identify if your terminal shell is `zsh` or `bash` by running `echo $0`, you should see `-zsh` or `-bash`. If you see `-bash`, run the previous command but substitute `~/.zshrc` with `~/.bashrc`. After you do this close and reopen the terminal (or you can do `source ~/.zshrc` or `source ~/.bashrc`.

After you do this, run `which mysql_config`, and you should see something like: `/usr/local/opt/mysql@8.0/bin/mysql_config`, although it is possible that your path may be slightly different. As long as you get *something*, you should be good.

Then run `python3 -m pip install "mysqlclient==1.4.6` again.

**Comment by gnodar01** [comment]
Also if the above fails, add the other lines detailed in the `brew` output above:

```
export LDFLAGS="-L/usr/local/opt/mysql@8.0/lib"
export CPPFLAGS="-I/usr/local/opt/mysql@8.0/include"
export PKG_CONFIG_PATH="/usr/local/opt/mysql@8.0/lib/pkgconfig"
```

Then close/reopen terminal or run the `source` command. Then finally run `brew install pkg-config` and try to install `mysqlclient` one more time.

**Comment by olasabet** [comment]
Hi Nodar, 

Thank you so much for the help and the suggestion with zoom. I will tell you where I am and you can decide if we it's a fast fix or we need to be online. 

- The great news is I have Cell profiler up and running from source !! many thanks again and I hope the steps I went through can help others. 

- All this work was intended for "ease of use" of active plugins such as Cellpose and Stardist, so after I got my CP running I followed the steps in https://plugins.cellprofiler.org/using_plugins.html and installed Cellpose as indicated but I got an error >> AssertionError: Torch not compiled with CUDA enabled . If this is something that can easily be fixed I would appreciate your support, but if you think this will need more back and forth, we can set a zoom call.

**Comment by gnodar01** [comment]
Great to hear the Cellprofiler installation went well.

You are on a mac, which doesn't support CUDA because nvidia gpus aren't compatible with macs (more or less). That will mean you have to run in CPU mode only.

I will close this issue. Please open a new one in [github.com/Cellprofiler/cellprofiler-plugins](https://github.com/CellProfiler/CellProfiler-plugins/), describing what you're trying to do, and where the CUDA assertion is happening (i.e. is it on the `pip install cellpose` step, or is it when you're actually trying to use the `RunCellpose` plugin within Cellprofiler, etc.

Once I get more info, we can take it from there.

**Comment by olasabet** [comment]
perfect, will do that. Thanks again for all your help :)
