### ISSUE TITLE
File => Export => Image Set List Listing...

### ISSUE THREAD

**Issue by ErinWeisbart** [CellProfiler/CellProfiler#4886]
When I File => Export => Image Set List Listing... I get a .csv where many columns are nan (I think all non-numeric columns I have extracted) despite having values in my Metadata module.

CP 4.2.6 built
Mac OS Sonoma

**Comment by ErinWeisbart** [comment]
Pipeline (renamed from .cppipe to .txt so it would upload)
[analysis_cellpose_NamesAndTypes.txt](https://github.com/CellProfiler/CellProfiler/files/14924698/analysis_cellpose_NamesAndTypes.txt)

**Comment by ErinWeisbart** [comment]
If I do `Image set matching method` == `Order` then all nonnumeric are nan but if I do == `Metadata` then it works for all Metadata columns that I use for matching but the ones I didn't use to match are still nan.

**Comment by bethac07** [comment]
Can you confirm if the columns that are NaN-ing are ones where all of the images in an image set should have the same value? Channel, for example, is one that often comes back NaN because each _image_ has a valid value but each _image set_ has several. 

>If I do Image set matching method == Order then all nonnumeric are nan but if I do == Metadata then it works for all Metadata columns that I use for matching but the ones I didn't use to match are still nan.

That often happens if there are one or more corrupted or otherwise weird images in your set - see this [recent forum post](https://forum.image.sc/t/cellprofiler-metadata-missing-from-the-output-sqlite-db/93572/2?u=bcimini)

If you can send us (here or offline) a set of images that reproduces, that would be super helpful!

**Comment by ErinWeisbart** [comment]
> Can you confirm if the columns that are NaN-ing are ones where all of the images in an image set should have the same value?
Ah, I didn't look closely and yes, the remaining NaN columns  in the `Metadata` matching are not single image set values.

> That often happens if there are one or more corrupted or otherwise weird images in your set 
If I try a few different subsets of the input data then `Order` matching works so I'm guessing that you're right about there being a corrupted/weird image in there somewhere.

Thanks for the clarification, sounds like the problem is on my end, not with CellProfiler :)
