### ISSUE TITLE
Ponder whether ReassignObjectNumbers needs a name change

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#632]
The module that is now ReassignObjectNumbers was formerly RelateObjects in CP 1.0, but the name doesn't make clear what it does. We're wondering whether another name change is in order.

@AnneCarpenter thinks SplitOrMergeObjects is a good name but is suspicious that we must've thought about that and decided against it for some reason.

**Comment by AnneCarpenter** [comment]
Note that one option within the module is to split or merge based on distance (neighbors) but the other option is per-parent so SplitOrMergeObjects is probably better than SplitOrMergeNeighbors.

**Comment by bethac07** [comment]
It's definitely a confusing name from an end-user point of view, I'm +1 for changing it (and agnostic between Anne's two preferences).

**Comment by braymp** [comment]
:+1: for changing as well. I think I prefer SplitOrMergeObjects; it's generic enough to capture what's there, while also encompassing other similar operations we might add later.

**Comment by AnneCarpenter** [comment]
I'd say with two of the world's best assay developers, plus a CP co-founder, agreeing on this, we should re-open this issue. Doing so now. SplitOrMergeObjects it is.

We should change the wording in the module - we carefully use "Unify" instead of "Merge" inside the module to reflect the possibility that we might be assigning the same object number to non-spatially-contiguous objects. But I think that it's ok to use Merge to describe that. Do others disagree?

We should also add some default text in the module window for this module (and also in the overview section of the help for the module) to state that the IdentifyPrimaryObjects module has options for more complex splitting and merging behaviors.

**Comment by mcquin** [comment]
A decision has been made. Closing in favor of https://github.com/CellProfiler/CellProfiler/issues/2697
