### ISSUE TITLE
Blow away existing preferences on CP installation

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler#838]
If the user has a prior version of CP already installed, some unwanted prefs may get inherited. This may be why the welcome screen might not appear, and I've seen this wreak havoc with the new string unicoding of the Default folders. Also, the outline color defaults have been changed and it would be good to make sure the defaults match the help refs.

It might be best to simply re-initialize the preferences when CP is installed.

**Comment by AnneCarpenter** [comment]
If I read things correctly, it sounds like we generally want to preserve preferences from one installation to the next. But, on a case by case basis we've decided that certain preferences are dangerous to transfer from one version of CP to the next because they cause problems. It sounds like the issue Mark mentions is an item that is in that category and thus is the remaining thing to be addressed to solve this issue.

**Comment by braymp** [comment]
The unicode issue is probably not quite the pain it used to be since I reported it in 2013, and probably more folks moved on to 2.1+ since then.

**Comment by AnneCarpenter** [comment]
Cool, let's close and if anyone objects we can reconsider.
